### ISSUE TITLE
Disconnected from FAF chat

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#1000]
[forever (3).zip](https://github.com/FAForever/client/files/1829511/forever.3.zip)
Client sort of freezes for a second, afterwards i'm disconnected from chat but can still use everything else on the client.

**Comment by JaggedAppliance** [comment]
[forever (4).zip](https://github.com/FAForever/client/files/1861009/forever.4.zip)

**Comment by Wesmania** [comment]
The chat was rewritten and the rewrite will be merged in eventually. We'll see about this issue once I merge the rewrite in.

**Comment by Wesmania** [comment]
Chat was rewritten, so I'll consider this closed for now.
