### ISSUE TITLE
KeyboardInterrupt does not close the client.

### ISSUE THREAD

**Issue by samuel-hxs** [FAForever/client#1001]
**I experienced...** Sending Keyboardinterrupt to faf startet from Terminal.
Exception window opens.

**how to reproduce** Open a terminal launch FAF from it. Using Ctrl-C.

**I expected...** Instead of opening bug Info window close the launcher.

**Where the bug is / What should be done** if you have a suggestion for fixing the issue, add it here.

**Comment by Wesmania** [comment]
Should be easy to fix, we just need to check for KeyboardInterrupt in the excepthook.
