### ISSUE TITLE
Switch to faf-java-api

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#1034]
The old Python API will soon be taken offline.

The only place where the client uses it is for the name history.
Please update it to use https://api.faforever.com/data/nameRecord instead.

**Comment by Wesmania** [comment]
I believe we fixed it already in #914, please confirm. We're using the /data/player endpoint with nameRecord fields for convenience, but I don't think it's a problem.
It's also included in the latest stable release, so we won't break it by turning the Python API off.

**Comment by micheljung** [comment]
Oh, cool, totally missed that :)
