### ISSUE TITLE
FA has died with error: execve: Permission denied

### ISSUE THREAD

**Issue by samuel-hxs** [FAForever/client#1044]
**I experienced...** write here what happened to you or what the current behavior is.
The game will not start because of missing permissions. 
Followed by a known bug. 
Platform is Ubuntu 18.

**how to reproduce** if explanation is needed to reproduce the problem, add it here
Download FAF version 0.16.1 from GitHub as ZIP. Extract and set it up. (UID, install dependency)
Starting and logging in.
Creating a new game or a new campaign. (might as well join one)
Getting error message 'FA has failed to start'.
In log the following appears: 
```
INFO:fa.game_process:Running FA via command:  /home/user/.PlayOnLinux/wine "/home/user/FAForever/bin/ForgedAlliance.exe" /mean 862.228 /deviation 109.085 /country  DE /init init_coop.lua /numgames 91 /log "/home/user/FAForever/logs/game.log" /nobugreport /savereplay "gpgnet://localhost/7995895/themyst.SCFAreplay" /gpgnet 127.0.0.1:34825
INFO:fa.game_process:Running FA via executable: /home/user/FAForever/bin/ForgedAlliance.exe
ERROR:client._clientwindow:FA has died with error: execve: Permission denied
ERROR:client._clientwindow:FA has failed to start
```

**I expected...** write here what you think the best behaviour should be
FAF starts the game.

**Where the bug is / What should be done** if you have a suggestion for fixing the issue, add it here.
ForgedAlliance has no executable permissions. The bug might be else where.
Leads to same behavior as #1007 on second try to start a game.

**Comment by Wesmania** [comment]
Are you able to run the ForgedAlliance.exe executable with wine manually? This looks like distro-specific behaviour for me, I'm able to run it through wine on Gentoo without any issues.
If it's possible to run the executable after chmod +x, I'll try and see why exactly the permissions aren't given. Oddly enough, it seems SupremeCommander.exe has correct permissions (at least on my end).

**Comment by samuel-hxs** [comment]
I found the error.
My configuration was wrong and there seems to be no check for it.

I added my wine settings to:

> ~/.config/ForgedAllianceForever/FA\ Lobby.ini

Excepted was a path to the wine ELF file.
But i gave a path to directory. 
Value for parameter 'exe' under category '[wine]'.

Maybe adding a check and error message for clarity if wine settings are wrong.

**Comment by Wesmania** [comment]
There's no GUI for wine settings just yet, I should really add some. I'll keep in mind to validate settings when I add it. Adding an error window when the game fails to start is a good idea too, I'll do that.
