### ISSUE TITLE
Clan leader = default channel moderator (admin) rights

### ISSUE THREAD

**Issue by MikZZ-faf** [FAForever/client#1047]
Hello.

Last few days somebody every time changes topic of my channel - kidding me, nothing bad but annoying. 

I wish the automatic moderator (admin) rights for clan channels to clan leaders will added right after the clan channel creating.  And reassign rights after the clan leader changing.

The second thing I wish to get in auto mode moderator (admin)  rights for my clan channel right now without any special actions.

I got some instructions how to get it by manual actions but it's really hard and Im sure other clan's leaders never heard about those instructions.

**Comment by Wesmania** [comment]
FAF client doesn't control any of this, it only acts as an IRC client. You'll have to talk with whoever administrates IRC (maybe owners of AeonCommander / UEFCommander). I'll let people on slack know, hopefully someone shows up here.

**Comment by Sheeo** [comment]
Please open an issue at @FAForever/clans
