### ISSUE TITLE
Game path problem

### ISSUE THREAD

**Issue by Apofenas** [FAForever/client#1051]
Hello.

This issue is kinda dumb and exists for years. When you first log into FAF it asks you to set directory to your game. Majority of new players simply double click on SCFA and than set directory to .exe file like SC:FA/bin so FAF doesn't accept it; instead you need to select folder and press "select folder" button - so confusing. I had this issue myself back in 2012 and still people constantly have it.

Can anything be done with it?

**Comment by Wesmania** [comment]
Probably. I'll check the code, it shouldn't be too hard.

**Comment by Wesmania** [comment]
The dialog shows directories only already, but I'll add an option to check directory parent for validity as well.

**Comment by Wesmania** [comment]
Fixed by 014a1cbb014fa447fc5aa.
