### ISSUE TITLE
Problem with FAF lobby.

### ISSUE THREAD

**Issue by FunnySqirrel** [FAForever/client#1056]
Black screen on some tabs (whats new, leaderboards, vaults). All elements works, but doesn't visible. 
Debug.log is attached
[debug.log](https://github.com/FAForever/client/files/2142911/debug.log)

**Comment by Wesmania** [comment]
This log doesn't say much. Could you attach forever.log?

**Comment by Wesmania** [comment]
Try running the client with --no-qt-angle-workaround flag, too.

**Comment by FunnySqirrel** [comment]
1) where to find forever.log?
2) sorry, but i dont know, how to do it.

**Comment by Wesmania** [comment]
If you run the client, all logs should be under HELP -> Show Logs.
You can set flags by right-clicking the executable, going to properties -> target and adding the flag after the executable path, as in `blahblah/FAForever.exe --no-qt-angle-workaround`.

**Comment by FunnySqirrel** [comment]
[forever.log](https://github.com/FAForever/client/files/2142994/forever.log)
forever.log. ok, problem with D3D

**Comment by Wesmania** [comment]
It looks like some issue with your DirectX. The flag might help, otherwise you can try reinstalling DirectX.

**Comment by FunnySqirrel** [comment]
yes, i reinstall windows few days ago... maybe directx. Which Dx is needed(dell inspiron 3521 with win7*64)?

**Comment by Wesmania** [comment]
DirectX 9.0c should be good.

**Comment by FunnySqirrel** [comment]
thank u. i try to do it

**Comment by FunnySqirrel** [comment]
OK. That works, WORKS!! (evil laugh))))
Thank you for your help.
