### ISSUE TITLE
Host game dialogue listing mods multiple times

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/client#1064]
This happens when you host a game with a featured mod, it seems the list of mods in the host games dialogue isnt cleared, so it gets appended to itself for each featured mod.

To reproduce:
1. host a game, take note of the number of mods in the host game dialogue
2. host a game with a different mod (i tried phantomx and claustrophobia) and take note of the number of mods in the game dialogue, the mods should all be listed twice.
3. repeat multiple times for even longer mod lists
4. this also applies to the map list, and each mod can be toggled on and off separately, not sure how that reflects in the game. the actual mod folder is unaffected.
5. reffafing fixes the issue, and then you can start all over again.

screenshots:
https://i.imgur.com/s6XKEIt.png equilibrium 1 - take note of the position of the scroll bar
https://i.imgur.com/s6XKEIt.png another equilibrium
https://i.imgur.com/GoXnfhK.png a third one
https://i.imgur.com/tcr5NXX.png fourth
https://i.imgur.com/EHjZCBR.png fifth, note that the scroll bar is low down now
https://i.imgur.com/XIHygYl.png sixth and final copy, the list is duplicated a total of 6 times in its entirety.

**Comment by Wesmania** [comment]
It seems I'm not clearing the mod / map list in the game hosting widget. Let's see if it gets fixed after I clear it.

**Comment by Wesmania** [comment]
Please confirm if https://ci.appveyor.com/api/buildjobs/5bacby5ddup1n3li/artifacts/dist%2FForged%20Alliance%20Forever-0.18.0-win32.msi fixes it.

**Comment by Wesmania** [comment]
Try https://ci.appveyor.com/api/buildjobs/3mts5vxax82a451j/artifacts/dist%2FForged%20Alliance%20Forever-0.18.0-win32.msi/
