### ISSUE TITLE
Searching for replay of a specific player takes forever or gives a 504 gateway timeout

### ISSUE THREAD

**Issue by Justify87** [FAForever/client#1069]
**I experienced...** a gateway timeout while searching for my replay on the replay vault

**how to reproduce** search for replay of EmptySlot on replay vault

**I expected...** my replays to show

**Where the bug is / What should be done** build better indexes on the replays table, update statistics of the table, rebuild indexes on the table. Or build a better query

**Comment by JJ173-zz** [comment]
![image](https://user-images.githubusercontent.com/17053495/43357473-17bcf2ce-927a-11e8-91ca-88924d1ef02d.png)

I have replays when I search. If you can reproduce, please leave a screenshot here.

**Comment by Justify87** [comment]
It works now. It did not work back then. I will update, when I can figure out how to reproduce. Maybe some query that runs forever on the database and blocks following queries. idk

**Comment by Wesmania** [comment]
I'd consider it fixed / server bug. I think we have one issue open that covers switching to jsonapi, too.
