### ISSUE TITLE
Enforced steam link rule

### ISSUE THREAD

**Issue by Krorenshima** [FAForever/client#1075]
When I tried logging in to either of the clients I got kicked out mainly because of the new enforced rule, however I have a physical copy of the game, so why would I need to buy the game again just for steam just to be able to play, so there should at least be a way to confirm that you either have a physical or digital copy of the game.

**Comment by Wesmania** [comment]
FAForever/server would be a better place to track this, since validation logic lives there. I don't think there's much of a chance for this to be implemented - it seems way too easy to spoof.

**Comment by Geosearchef** [comment]
I want to add that you can use the physical CD key to recieve a steam copy of the game.
