### ISSUE TITLE
NoModuleFound 'sip'

### ISSUE THREAD

**Issue by Polygon-Dust** [FAForever/client#1080]
Unable to run FAForver on linux(specs below). While using both AUR and git the error "ModuleNotFoundError: No Module named 'sip'" occurs. AUR has another user who noted the issue back in late 2018. 
--------------------------------------------More Info below-----------------------------------------------------------
--------------------------------------------AUR---------------------------------------------------
"==> Starting prepare()...
Note: checking out '0.18.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8bbcdf50 *fix* changelog entries for 0.18.1
==> Starting pkgver()...
==> Starting build()...
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
==> ERROR: A failure occurred in build().
    Aborting...
"
------------------------------------------GitHub------------------------------------------------
"# python setup.py
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
------------------------------------------System Specs----------------------------------------------------------------
"
neofetch
OS: Arch Linux x86_64 
Kernel: 4.20.4-arch1-1-ARCH 
Uptime: 2 hours, 19 mins 
Packages: 578 (pacman) 
Shell: zsh 5.7 
Resolution: 1600x900, 1600x900 
DE: Xfce 
Theme: Adwaita-dark [GTK2], Adwaita [G 
Icons: Paper-Mono-Dark [GTK2], Adwaita 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: AMD Ryzen 7 1800X (16) @ 3.023GHz 
GPU: AMD ATI Radeon RX 470/480/570/570 
Memory: 1738MiB / 16032MiB 
"
-------------------------------------Other AUR user with same/similar issue.---------------------------------------
" Win8Error commented on 2018-09-07 09:48

Compile failed:

==> Beginne prepare()... Hinweis: Checke '0.18.1' aus.

Sie befinden sich im Zustand eines 'losgelösten HEAD'. Sie können sich umschauen, experimentelle Änderungen vornehmen und diese committen, und Sie können alle möglichen Commits, die Sie in diesem Zustand machen, ohne Auswirkungen auf irgendeinen Branch verwerfen, indem Sie einen weiteren Checkout durchführen.

Wenn Sie einen neuen Branch erstellen möchten, um Ihre erstellten Commits zu behalten, können Sie das (jetzt oder später) durch einen weiteren Checkout mit der Option -b tun. Beispiel:

git checkout -b <neuer-branchname></neuer-branchname>

HEAD ist jetzt bei 8bbcdf50 fix changelog entries for 0.18.1 ==> Beginne pkgver()... ==> Entferne existierendes $pkgdir/ Verzeichnis... ==> Beginne build()... Traceback (most recent call last): File "setup.py", line 5, in <module> import sip ModuleNotFoundError: No module named 'sip' ==> FEHLER: Ein Fehler geschah in build(). Breche ab...</module>
"
-----------------------------------Solution-----------------------------------------------------------------------------------
ARCH AUR needs python-sip or python2-sip added to dependencies.

**Comment by Wesmania** [comment]
You'll have to ask @muellni for that, he's maintaining the arch aur. It's not part of the repo. Try contacting him on FAF forums.
