### ISSUE TITLE
PyQt5 import error (linux)

### ISSUE THREAD

**Issue by geekingfrog** [FAForever/client#1081]
**I experienced...**
Crash at startup on the tag 0.18.1 (8bbcdf5051be10507629869d6a1d15a9a7a8f844) as well as develop (b15bba968958c61ea039f5082ccdb4e53f733de0) with the error message:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 55, in <module>
    from PyQt5 import QtWebEngineWidgets
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/lib/python3.7/site-packages/PyQt5/__init__.py)
```

**how to reproduce**
I'm running faf client on archlinux. Everything was going alright until I updated pyqt. Here are the relevant pacman logs:

```
[2019-02-16 09:06] [ALPM] upgraded pyqt5-common (5.11.3-4 -> 5.12-2)
[2019-02-16 09:06] [ALPM] upgraded python-sip-pyqt5 (4.19.13-1 -> 4.19.14-1)
[2019-02-16 09:06] [ALPM] upgraded python-pyqt5 (5.11.3-4 -> 5.12-2)
[2019-02-16 09:06] [ALPM] upgraded python2-sip-pyqt5 (4.19.13-1 -> 4.19.14-1)
[2019-02-16 09:06] [ALPM] upgraded python2-pyqt5 (5.11.3-4 -> 5.12-2)
```

**I expected...**
client starts as usual

**Comment by Polygon-Dust** [comment]
Are you using AUR or following the instructions on GitHub(when you did install)? I had the problem when I went to install FAF on a new computer.

**Comment by geekingfrog** [comment]
I'm using the github install directly.

**Comment by Wesmania** [comment]
It seems that QtWebEngine is available in Arch as a separate package. Do you have it installed? Are you able to run `from PyQt5 import QtWebEngineWidgets` directly in Python shell?

**Comment by geekingfrog** [comment]
Here are all the pyqt package I have:
```
-> % pacman -Q | rg -i pyqt
pyqt5-common 5.12-2
pyqtwebengine-common 5.12-2
python-pyqt5 5.12-2
python-sip-pyqt5 4.19.14-1
python2-pyqt5 5.12-2
python2-sip-pyqt5 4.19.14-1
```

And when running directly from python shell (in the `venv`) I still get the import error:
```
>>> from PyQt5 import QtWebEngineWidgets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/usr/lib/python3.7/site-packages/PyQt5/__init__.py)
```

**Comment by Wesmania** [comment]
There's also a python-pyqtwebengine package available I think, do you have it installed?

**Comment by geekingfrog** [comment]
Ah, good catch. I installed that package and that fixed my issue.
