### ISSUE TITLE
Online Replay Vault not loading anything since transition to ICE

### ISSUE THREAD

**Issue by DBazer** [FAForever/client#1083]
I can't quite recall the exact date when I noticed the replay vault in the python client ceased to load anything, but it was either the day faf officially transitioned to ICE and the Java client or in the following couple days. Likely the 22nd of April.

Title has it all pretty much, replay vault is indefinitely stuck on "Searching...", be it the default recent replays as you launch the client or any search query you input.

I'm personally far from a fan of the replay vault in Downlord's client, or at least until some major redesigns, so with that and many other reasons I'd rather keep using the python client but with the replay vault not working there's little use for it, barring the local replay vault which is currently broken in Downlords.

And yes, the replay vault is still broken in the Python client with today's 0.18.3 update.

My motivation to spend time on faf dropped drastically since the transition to ICE and namely the Java client :'(
If anyone can fix the replay vault, that would be massive! The recent update allowing you to connect to ICE with it is already immense progress, we're just missing the replay vault now to get to where we were before, functionality wise.

Cheers :)
![xvc](https://user-images.githubusercontent.com/48331623/56761875-1de11380-67a7-11e9-9dc6-233f0ebc7d0c.jpg)

**Comment by Wesmania** [comment]
Not strictly a client bug, just one legacy server that only py client uses was shut down. I'll see what can be done about that.
