### ISSUE TITLE
Fa client will not log in

### ISSUE THREAD

**Issue by Sherwood321** [FAForever/client#1090]
Having downloaded the FA Client on 30/05/2019 and attempting to login with valid credentials, I receive an incorrect login message.

Reproducable everytime. I have even changed my password on the faforever.com website and logged in successfully but the client gives me the same login error message.

Screenshot attached.

![image](https://user-images.githubusercontent.com/5501195/58670367-af0f5100-8336-11e9-9f90-34d63e8e74fb.png)

**Comment by Brutus5000** [comment]
Do **not** user your email address to login! Please try with the correct username.

**Comment by Sherwood321** [comment]
@Brutus5000 all good thank you.
