### ISSUE TITLE
Update not downloadable since FAF version 3741

### ISSUE THREAD

**Issue by Ysae1** [FAForever/client#1133]
Hello,

I created an account to report a problem with the python client. I hope this is the right place for it, because I'm new to GitHub or doing bug reporting there:

Since Update 3741 the python client isn't able anymore to download and updated FAF files. That means you are stuck on version 3740 and cannot play games online anymore.

How to reproduce: Just go to the "Play" tab of the client and try to host or join a game. You then get an error message stating "Failed to download Update from https://content.faforever.com/legacy-featured-mod-files/..."

I expect there to be an issue with FAF doing some changes to the servers in 3741.
Changelog of 3741: https://github.com/FAForever/fa/blob/deploy/fafdevelop/changelog.md#game-version-3741-21st-of-august-2022

Unfortunately I'm a total noob in this kind of matter so I didn't try getting into it an figuring it out by myself. But I hope that someone who knows more about this client and about programming in general might be able to fix it more easily.
Off-topic remark: I wanted to express my appreciation for Gatsik(?) for making this client. It's got such a tidy and easy to comprehend interface. And I hope it gets to live another day :)

**Comment by Brutus5000** [comment]
This is a known problem with work in progress (see https://github.com/FAForever/client/pull/1132)
