### ISSUE TITLE
Win Taskbar Progress

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/client#116]
Show Progress in Window Taskbar:
http://forums.faforever.com/forums/viewtopic.php?f=42&t=8679

http://qt-project.org/doc/qt-5/qtwinextras-overview.html
http://qt-project.org/doc/qt-5/qwintaskbarprogress.html

**Comment by arkitect-dev** [comment]
closing this as #116 deals with notification for full lobby, which is the only meaningful suggestion here. download progress is not long running enough to make this worthwhile
