### ISSUE TITLE
Run Game on MacOS

### ISSUE THREAD

**Issue by thygrrr** [FAForever/client#13]

**Comment by Wesmania** [comment]
Not a lobby issue.

**Comment by Sheeo** [comment]
Why not? Shouldn't it provide an option to run the game through wine if applicable?

**Comment by Wesmania** [comment]
If this is the scope here, then we're covered by the client running on Linux. If we get the client running on MacOS, then we get running the game through wine for free.

**Comment by Sheeo** [comment]
Unless something major happened; the client runs on MacOS quite fine :) We just don't produce builds for it, I believe. But all right; sounds like it's covered by the linux scope indeed.

**Comment by Wesmania** [comment]
Client running on MacOS is news for me - got any links?
