### ISSUE TITLE
Better nat traversal

### ISSUE THREAD

**Issue by faf5678** [FAForever/client#134]
the faf server really only needs to communicate the target address:port to the lobby and
a configuration (how many packets to send etc.) and not every single packet. lobby reports back statistics on what was sent and received.
(to clarify: "SendNatPacket" and "ProcessNatPacket" are being made obsolete/refined)

benefit:

* move complexity out of the server
* less traffic, makes more sense
* can be designed so that it allows the server full control as before when needed

additional improvements

* rtt measurements (ipv4/6 best path discovery, possibly peer-acting-as-proxy)
* seq/ack style messages so that the sender can see for itself which packets arrived

**Comment by Sheeo** [comment]
Is there going to be an implementation for this, or is it safe to close?

**Comment by faf5678** [comment]
close it. if my $$$ job becomes dull again, i might reopen this.
