### ISSUE TITLE
Forum RSS Feed Length

### ISSUE THREAD

**Issue by madformuse** [FAForever/client#150]
Any chance of increasing the number of posts returned by http://forums.faforever.com/forums/feed.php ? I use the feed to keep up with what's going on in the community but it only seems to contain the posts for the last 12 hours so unless I log on once every twelve hours I miss some stuff.

I think RSS clients keep track of what they've already seen so would there be any problem increasing it to one week?

**Comment by IDragonfire** [comment]
@madformuse Is this still relevant?
It should be possible:
https://www.phpbb.com/support/docs/en/3.1/kb/article/faq-phpbb-atom-feeds/

**Comment by arkitect-dev** [comment]
this isn't a client issue so does not belong here. if this is still an issue hit up legiondarrath as it's forums related
