### ISSUE TITLE
Maps with non-ascii characters break ability to host

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#171]

**Comment by duk3luk3** [comment]
Example please?

**Comment by 1-alex98** [comment]
U can't have Emojis in it

**Comment by Wesmania** [comment]
Still doesn't tell us much - in what way does it break? Do you get the exception window? If you do, can you post your faforever.log after the error?

**Comment by Wesmania** [comment]
I'll consider this abandoned, reopen if issue persists.
