### ISSUE TITLE
Passwords not salted.

### ISSUE THREAD

**Issue by Frozen-byte** [FAForever/client#173]
The passwords are not salted.
At least the IRC Password, as you may see here:
https://github.com/FAForever/lobby/blob/develop/src/chat/_chatwidget.py#L277

I think we don't have to mention the security leak resulting on not, salted Password-Hashes.

**Comment by IDragonfire** [comment]
Even worst:
https://github.com/FAForever/client/blob/develop/src/vault/__init__.py#L68

**Comment by IDragonfire** [comment]
btw, the password in the chat is double hashed :D 
https://github.com/FAForever/client/blob/develop/src/client/loginwizards.py#L63

related to
https://github.com/FAForever/api/issues/1
https://github.com/FAForever/server/pull/23

**Comment by ChrisKitching** [comment]
Not a client bug: this needs solving at the server. The ridiculous client-side-hashing is something we're now stuck with (given our database of existing accounts), and we must build a sane salting mechanism atop this on the server.

I have mostly completed this task anyway, so let's clear this issue out of this incorrect repo.

I agree, this is nuts and quite urgent to resolve.
