### ISSUE TITLE
Connection problem link broken

### ISSUE THREAD

**Issue by FireEmerald** [FAForever/client#174]
The following link which is shown if you had trouble connection to some players doesn't work:
* http://www.faforever.com/mediawiki/index.php?title=Connection_issues_and_solutions

**> File not found.**

![example](https://cloud.githubusercontent.com/assets/1107939/6096806/227eb4a6-afa5-11e4-8bc5-ba1fd9c731e3.JPG)

**Comment by micheljung** [comment]
Already done by Sheeo

**Comment by Sheeo** [comment]
Right, this is fixed on FAForever/server at develop. Should be live soon.
