### ISSUE TITLE
Reintroduce matchmaker

### ISSUE THREAD

**Issue by ghost** [FAForever/client#181]
It would be nice if the same system that is used for 1v1 ladder matches would work for 2v2 ladder matches.

**Comment by Sheeo** [comment]
Hi @silentsnooc, thanks for filing this. The plan is to work on reintroducing the matchmaker. I'll update the title accordingly and file an accompanying issue on FAForever/server

**Comment by silentsnooc** [comment]
Alright @Sheeo! I am insanely busy at the moment and covered up with work and stuff for university. I guess I will be busy for the next week too but the week after that should be fine for me to start digging into the client a little. :)

**Comment by Sheeo** [comment]
Sounds awesome @silentsnooc! :) Hope you're doing well at university.

**Comment by silentsnooc** [comment]
@Sheeo Thanks, I'm fine but just having quite a work load at the moment to get rid of :P

**Comment by madformuse** [comment]
Is it the idea that requesting a 2v2 would result in you being pared with someone you didn't know? I saw a post on the forums where Shepard said it would cause rage but what do you guys think?

**Comment by silentsnooc** [comment]
@madformuse Well I was more thinking about something like first create a group with somebody - like sending a group request - and only then you can click on "start ladder match" for example. The only thing is that I don't really know how many people would like to play 2v2s with a friend in a ladder match. 

My bug problem at the moment is time. I thought I'd have some time in the Easter break but it turned out I didn't. Now that the university started again I'm not sure if I'm going to have time before summer :/ Sorry, Sheeo btw.

**Comment by madformuse** [comment]
Yeah that makes sense although as you say I would imagine pre-formed groups would be a lot harder to match. Saying that though, someone else wouldn't need to be searching if they got the notification "Someone in your range is looking for a 2v2 game" (obviously this should make sure your team mate is online at the same time. Maybe is should notify the other party if you say you'd like to play?

It would make sense to me to also be able to form multiple teams with different people, each group having a name. That way there would be a lot more possible matches.

My problem is I can't get the right Python modules installed (py/libgit2), stupid c++ programmers :-). I intend to seek some technical support!

**Comment by madformuse** [comment]
@silentsnooc sorry I forgot to tag you. Is that the normal thing to do on GitHub?

**Comment by silentsnooc** [comment]
@madformuse Well yeah that makes sense. Imho one should "register" a team such that the team gets their own ranking. That way you can also have multiple groups if you have more people who you want to play ladder matches with. Also that way the team can only be as strong as the weakest link in the chain. 

Regarding those Python modules @Sheeo should be able to help you but afaik the client now does deliver those libraries itself so (if I am not mistaken here) you should not need to install libgit2. I too had a lot of problems installing libgit2 - in fact I never succeeded :D
