### ISSUE TITLE
Error when i open replay tab

### ISSUE THREAD

**Issue by Cheyans** [FAForever/client#185]
As in title, when i click the replay tab, this error pops up, but i can still continue and open replays(live,local,online) without issues

Error: http://pastebin.com/YmYwkPHR
(Some of) Faforever log: http://pastebin.com/TSWyLdFa

**Comment by Sheeo** [comment]
Seems to be a server error, but the client is also not being very helpful in saying what went wrong.

Filing a bug at FAForever/server

**Comment by arkitect-dev** [comment]
closing as not occurring in current client and this issue is a year old
