### ISSUE TITLE
Live replays are displayed in the vault if you search for replays

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#186]
![issue](https://cloud.githubusercontent.com/assets/8906373/6759865/7aa1e27e-cf3b-11e4-9409-3bfd6bf69853.PNG)

These are all live replays. The time is put to 10hours, and they are not watchable, causing a error if you try.
They don't show if you just open the replay vault, but do show if you press the search - it doesn't matter what you search for, leaving the options blank shows all livereplays + replays, searching for 1v1 automatch will show 1v1 automatch livereplays and replays, and so on.

**Comment by Sheeo** [comment]
Interesting find. Should be moved to FAForever/server repo.

**Comment by VoRGoR** [comment]
How do I do that :D

**Comment by Sheeo** [comment]
I did it, marking this one as closed :)
