### ISSUE TITLE
IRC: Listen instead of polling

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#191]
I heard you have problems with server load.

Well, I didn't have a deep-look into the code so I may be wrong, but from [this line](https://github.com/FAForever/client/blob/develop/src/chat/_chatwidget.py#L40) I take that the client polls for new messages every 300ms. That would be more than 300 request per second with 100 users - outch.

But maybe that polling is for something else? I don't know.

**Comment by Sheeo** [comment]
That isn't how the IRC protocol works.

This pollrate is apparently how often the gui thread will poll the irc library for messages, and this is entirely crazy, yes.

**Comment by JeroenDeDauw** [comment]
Do IRC clients really have higher delays than that? I never noticed...
