### ISSUE TITLE
Show map size in ladder selection menu

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#196]

**Comment by IDragonfire** [comment]
We should maybe have a central map selection dialog,
that we can reuse in other widgets (e.g. host game)
my draft:
![ladder_map_selection2](https://cloud.githubusercontent.com/assets/1217999/6979409/80cb72de-d9e3-11e4-8527-b01ad99b62a3.png)

More UI Concepts:
https://www.dropbox.com/sh/pqkde9sjgi081nh/AABdEx4Zdo35OcRfM8-V4ZQ3a?dl=0

**Comment by IDragonfire** [comment]
The concept is old maybe the select map checkbox can be placed in the left top corner of the "map widget"

**Comment by IDragonfire** [comment]
related to
https://github.com/FAForever/client/issues/65

**Comment by ChrisKitching** [comment]
Ladder map selection is no longer a thing.

**Comment by Sheeo** [comment]
The ladder pool however, still is.

Having the sizes in a replacement display would be nice.
