### ISSUE TITLE
Eye of the Storm Tutorial is Broken

### ISSUE THREAD

**Issue by eurobuzz** [FAForever/client#202]
**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance

**Home Directory:** C:\Users\eurobuzz\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "tutorials_tutorialswidget.pyc", line 59, in finishReplay
  File "fa\exe.pyc", line 169, in replay
KeyError: 'uid'

}}}

Possibly related to #87 ?

I have tried to launch the tutorial on two different computers and neither work. This isn't something that broke recently though, as I tried to launch the tutorial months ago and same error, so it has not worked for a while now, at least for me. All other tutorials work.

**Comment by Sheeo** [comment]
On first glance, this is actually a serverside issue. I'll need to verify.

**Comment by arkitect-dev** [comment]
can this be closed now?

**Comment by Wesmania** [comment]
The exception is probably completely obsolete, so yeah.
