### ISSUE TITLE
Replacement for ingame CPU benchmark

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#203]
We need a suitable replacement for the CPU benchmark that adresses the following concerns:

- Current CPU benchmark helps lock up the UI
- It's not very representative of in-game performance

Original issue at FAForever/fa#254

**Comment by micheljung** [comment]
why?

**Comment by Sheeo** [comment]
The original issue at FAForever/fa/issues/254 details reasons the reasons. I'll update the issue description here.

**Comment by Stupinator** [comment]
can we keep track of performance with respect to map size and number of players. so the benchmark would be the average of the performance on that map size with that number of players.

**Comment by Sheeo** [comment]
Unless we benchmark every game, then no.

I don't see how that would be useful either; a generalized metric should suffice.

**Comment by Stupinator** [comment]
ya, every game was what i had in mind. or last 10 games (in case he changed a pc or something).
that way we dont have to generalize for odd cases.

**Comment by Androish** [comment]
I just had an idea regarding benchmarking. Seeing any synthetic test will be prune to be flawed. Can't we collect and store simspeed data from ren_shownetworkstats to make a rating of individual CPU's.
Every time you are in a game your simspeed will be compared to everyone else in the games simspeed. This would make it possible to make a pretty decent ranking of CPU's no?
Maybe even stored by CPU model, incase users use more than one PC. (but I guess a program needs admin privileges to get such data? Maybe it can be collected once per client install?)

If this is even possible it wont use any additional resources when the client is loading. And would be a more accurate in regards to actual simspeed.

Probably way to much work for little gain but just incase anyone thinks it is a good idea and wants to implement it. I will put it out there :)

**Comment by micheljung** [comment]
trueskill for CPU rating :D

**Comment by Sheeo** [comment]
Sounds like a very ad hoc solution @Androish.

If we can grab the data from the UI state (I'm not sure we can do this -- I believe the engine renders the box?) then sure, it would make sense to gauge the performance of player machines that way.

**Comment by aeoncleanse** [comment]
Actually I think this is an excellent proposal. It would take some time to gather the data needed, but if we were to harvest this data for a month or so, we'd be able to make a pretty damned accurate CPU hierarchy chart and then assign ratings based on CPU model. Sure beats what we have.

**Comment by arkitect-dev** [comment]
this is a huge amount of work for little benefit, not only would we have to harvest the sim speed data from games but we'd have to have profiles for each machine for each player. I just can't see it being worth the time it would take to implement
