### ISSUE TITLE
Enable UPnP by default

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#206]

**Comment by Eximius** [comment]
It has used upnp by default for forever....

**Comment by IDragonfire** [comment]
:+1:

**Comment by Eximius** [comment]
Well, okay, I just checked the code. It was my belief that it was and for some reason still is the case in new-protocol-py3.

**Comment by Sheeo** [comment]
I've received reports that this isn't the case on develop, needs verification.

**Comment by IDragonfire** [comment]
UPnP is by default off in c1ae59c08bd58321cc01ef6a112fe45d67ec1245
https://github.com/FAForever/client/blob/c1ae59c08bd58321cc01ef6a112fe45d67ec1245/src/client/_clientwindow.py#L808

**Comment by Sheeo** [comment]
https://github.com/FAForever/client/commit/13a499f3931fbdeb89210057af46ef312b4ecc2d
