### ISSUE TITLE
Data corruption while reading file from server

### ISSUE THREAD

**Issue by wsargent** [FAForever/client#207]
```
**FAF Username:** viridian

**FAF Version:** 0.10.122

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\Steam\steamapps\common\supreme commander forged alliance

**Home Directory:** C:\Users\wsargent\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 813, in handleAction
UnicodeEncodeError: 'ascii' codec can't encode characters in position 51-91: ordinal not in range(128)

}}}
```

This may be related to http://forums.faforever.com/forums/viewtopic.php?f=3&t=9540

**Comment by Eximius** [comment]
@Sheeo This is that bug again. Seemingly coming from server-side.

**Comment by Sheeo** [comment]
Presumably yes, this shouldn't occur with the new implementation of the QDataStream protocol, and not in the future with new protocol.

Will close this on completion of https://github.com/FAForever/server/issues/83

**Comment by Sheeo** [comment]
Work on the referenced issue finished, but it remains to be proven whether this will solve this particular client issue. Leaving open for future confirmation.

**Comment by wsargent** [comment]
@Sheeo what version FAF will this fix be in?
