### ISSUE TITLE
Client crashes because of conflicting LIBEAY32.dll

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#211]
I'm not 100% sure about what I write here, d-_-b has more details as it happened to him. I just guessed in the right direction.

The uid.dll depends on LIBEAY32.dll which seems to be part of openssl. It also comes with FAF.
So if you have LIBEAY32.dll in your PATH (probably in C:\Windows\System32) and the order is somehow "wrong", the client crashes since the uid.dll is icompatible with the loaded LIBEAY32.dll.

Workaround is to remove/rename the one in System32.

**Comment by Sheeo** [comment]
Unclear what we should do here, we do ship the LIBEAY32.dll in the application folder. I don't see how the lookup order could be wrong.
