### ISSUE TITLE
A new link on the top bar of aeolus

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#214]
I'm going to construct a page detailing the mod team, links to rules, forum mods, all roles, ways to report problems etc etc etc

When it is done, I want it to be super obvious from faf to be seen and navigated too

Would be nice : )

**Comment by arkitect-dev** [comment]
did you ever write this up? is there a link to point to or is this abandoned?

**Comment by ghost** [comment]
I guess this one should be closed too. I see some links in top of aeolus and no answer from VorGor
