### ISSUE TITLE
highlight chat channel tabs an indicator if there is a new message

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/client#215]
Doesn't have to be anything special, give the tab a different colour or shade of the existing colour or highlight it slightly.

**Comment by madformuse** [comment]
This would be nice for other tabs too like when there's a new tournament. I think it might be good as a number and not just a different colour.

**Comment by madformuse** [comment]
Oh sorry, you mean each IRC channel tab and not just the main faf chat tab? Are you talking about any message or ones addressed to you only? Might be permanently highlighted if you mean the former :)

**Comment by Zockyzock** [comment]
Both would be great. Highlight specific tabs (whats new, tourny) when there is something new, and highlight irc channel tabs: two different kinds of highlights for new message, or messages addressed to you. 

I don't think perma highlight is a problem except for aeolus, which is the active channel (and thus doesn't need a highlight) in most cases anyway. The highlight should still be not too flashy, just some form of indicator that there is a new message in non-active channels.

**Comment by Wesmania** [comment]
Done!
