### ISSUE TITLE
Mod Vault Shows a Limited Number of Mods

### ISSUE THREAD

**Issue by CodingSquirrel** [FAForever/client#219]
This is an issue that seems to come up very often when talking about mods, because it's pretty unintuitive as is. Currently, when searching for mods in the vault, if you type something in it will only show you a subset of mods. I believe it's determined by having >6 likes. It also gives no indication of the fact that what you're seeing isn't the full list, leaving the user confused that they can't find a mod. Is there any reason for this cutoff? Is there a better way we can communicate this to users?

The other portion of this is that hitting enter, a common paradigm when searching for something, actually doesn't do anything. You have to physically click the Server Search button to do a full search. Instead, the return key should initiate the search the same as hitting the button.

**Comment by CodingSquirrel** [comment]
I don't have my desktop environment set up to work on the client code, but I think adding the search on enter would be fairly simple. It looks to me like it could be done by adding "self.searchInput.returnPressed.connect(self.localSearch)" below line 106 here https://github.com/FAForever/client/blob/23f09dfe8bef65e49018a20d0c5c45876c373501/src/modvault/__init__.py#L106

**Comment by CodingSquirrel** [comment]
I made a quick mockup of a small notification to let you know when you're using the local search. It would show up whenever you type something into the input box, and would go away when you use the full search.

**Comment by ChrisKitching** [comment]
Oh wow this UI is terrible.

Fancy poking it, squirrel? Nag sheeo about helping get your environment set up: the client really needs some work doing. It mostly looks like the server did before sheeo deleted 2/3 of it :P

**Comment by Sheeo** [comment]
Indeed the client needs a helping hand. Most importantly we need the current develop branch up to speed with master and vice versa. Regarding setting up a development environment, it should be apparent from the readme :)

**Comment by arkitect-dev** [comment]
closing as mod searching and <6 likes working in current client
