### ISSUE TITLE
Adding people connecting by IRC as friends is not saved

### ISSUE THREAD

**Issue by quark036** [FAForever/client#221]
If you add someone who is connecting via irc (faint and greyed out names), as a friend, then close FAF, when you reopen it, it doesn't recognize them as a friend.

**Comment by Sheeo** [comment]
Can't do this reliably since IRC accounts are technically unauthenticated (Related to FAF) as of right now.

**Comment by ChrisKitching** [comment]
Unsupported by server protocol: a client ID is required to add a friend, something which is not present for IRC users.

**Comment by Sheeo** [comment]
Indeed to get this working we need to do more IRC integration -- this is technically possible, but most certainly not a priority at the moment.
