### ISSUE TITLE
Impossible to host COOP campaign

### ISSUE THREAD

**Issue by AggonyRiksosten** [FAForever/client#222]
I try to host a coop-game, it fails the update, I get this message. I tried loading a coop replay, got the update to go a bit further, but it still crashes. Just a bit later. It was working just fine before the latest patch.

**FAF Username:** AggonyRiksosten

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance

**Home Directory:** C:\Users\ARIVIDPC\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

**Comment by Sheeo** [comment]
Delete your game data and try again (The lobby provides a utility option for this under Options -> Clear -> Game files)
