### ISSUE TITLE
Coop Instant Crash (Opens Ticket Window)

### ISSUE THREAD

**Issue by Redfox442** [FAForever/client#223]
Hello! Thanks guys for working tirelessly on the issues with the coop and vanilla campaigns!

Any time I try to host or join a coop game this is the error ticket I recieve:

**FAF Username:** Redfox

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance

**Home Directory:** C:\Users\Robin\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "fa\updater.pyc", line 899, in readDataFromServer
  File "fa\updater.pyc", line 819, in handleAction
  File "fa\updater.pyc", line 707, in applyPatch
  File "shutil.pyc", line 119, in copy
  File "shutil.pyc", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\\ProgramData\\FAForever\\cache\\patchedFile'

}}}

Then when I click continue I get a screen that says faf couldnt complete the upgrade, followed by all this:

Update started at 2015-08-13 22:54:42
Using game path: C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance
Using appdata: C:\ProgramData\FAForever
Connected to update server at 2015-08-13 22:54:43
writeToServer(GET_FILES_TO_UPDATE, [FAF])
handleAction(LIST_FILES_TO_UP) - 324 bytes
Files to update: [ForgedAlliance.exe, init_faf.lua, init_ladder1v1.lua, GDFBinary.dll, SupComDataPath.lua, SupComDataPathFAF.lua, init_nonxt.lua]
writeToServer(UPDATE, [bin, init_nonxt.lua, 16da7063ae3309c154a2c544f559b3a9])
writeToServer(UPDATE, [bin, GDFBinary.dll, 6f57f59c2e705d7a5a02d49e3915cb26])
writeToServer(UPDATE, [bin, init_faf.lua, 68ab7cb504a9a6c349f748c2d5db38c3])
writeToServer(UPDATE, [bin, ForgedAlliance.exe, 68174e5736aaaa8e066e32244d4fa02d])
writeToServer(UPDATE, [bin, SupComDataPath.lua, 55ac1ef97845f2291da64b830299331e])
writeToServer(UPDATE, [bin, SupComDataPathFAF.lua, 962c9d1327657d77184adcf358c628f1])
writeToServer(UPDATE, [bin, init_ladder1v1.lua, ea96ac9cec88af29c08556c96465acfe])
handleAction(UP_TO_DATE) - 56 bytes
file : init_nonxt.lua
init_nonxt.lua is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : GDFBinary.dll
GDFBinary.dll is up to date.
handleAction(UP_TO_DATE) - 52 bytes
file : init_faf.lua
init_faf.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : ForgedAlliance.exe
ForgedAlliance.exe is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : SupComDataPath.lua
SupComDataPath.lua is up to date.
handleAction(UP_TO_DATE) - 70 bytes
file : SupComDataPathFAF.lua
SupComDataPathFAF.lua is up to date.
handleAction(UP_TO_DATE) - 64 bytes
file : init_ladder1v1.lua
init_ladder1v1.lua is up to date.
Updates applied successfully.
writeToServer(GET_FILES_TO_UPDATE, [FAFGAMEDATA])
handleAction(LIST_FILES_TO_UP) - 374 bytes
Files to update: [faforever.faf, effects.nx2, env.nx2, loc.nx2, lua.nx2, meshes.nx2, modules.nx2, projectiles.nx2, schook.nx2, textures.nx2, units.nx2, etc.nx2]
writeToServer(UPDATE, [gamedata, schook.nx2, 15afbb3bcca108dd0bfe6138fd954a63])
writeToServer(UPDATE, [gamedata, effects.nx2, dbeab47fa2a728f51692c7dfba13b171])
writeToServer(UPDATE, [gamedata, modules.nx2, 38f12974e5e0898d9188c2aae1edc47a])
writeToServer(UPDATE, [gamedata, lua.nx2, 4d0dc5b8a56096ee264365684e4c8500])
writeToServer(UPDATE, [gamedata, textures.nx2, c6f254d327423160cc52135e5ad89c96])
writeToServer(UPDATE, [gamedata, etc.nx2, c86923bc4659d9c6b583bc12005616bb])
writeToServer(UPDATE, [gamedata, env.nx2, 25d0a20db863cb7b1a578e543a375ee3])
writeToServer(UPDATE, [gamedata, meshes.nx2, 2cf16b2c841bca53122c7efd3949b691])
writeToServer(UPDATE, [gamedata, faforever.faf, 51c196294638c22071dc8ee01e55771e])
writeToServer(UPDATE, [gamedata, loc.nx2, bb2ee463674b6d06ef8e399821fb86ad])
writeToServer(UPDATE, [gamedata, projectiles.nx2, f3bdd4171255fd71fdefbf1d7bf0cffb])
writeToServer(UPDATE, [gamedata, units.nx2, 3e0d38d26313bbffbdc39b0ed731c78f])
handleAction(UP_TO_DATE) - 48 bytes
file : schook.nx2
schook.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : effects.nx2
effects.nx2 is up to date.
handleAction(UP_TO_DATE) - 50 bytes
file : modules.nx2
modules.nx2 is up to date.
handleAction(UP_TO_DATE) - 42 bytes
file : lua.nx2
lua.nx2 is up to date.
handleAction(UP_TO_DATE) - 52 bytes
file : textures.nx2
textures.nx2 is up to date.
handleAction(UP_TO_DATE) - 42 bytes
file : etc.nx2
etc.nx2 is up to date.
handleAction(UP_TO_DATE) - 42 bytes
file : env.nx2
env.nx2 is up to date.
handleAction(UP_TO_DATE) - 48 bytes
file : meshes.nx2
meshes.nx2 is up to date.
handleAction(UP_TO_DATE) - 54 bytes
file : faforever.faf
faforever.faf is up to date.
handleAction(UP_TO_DATE) - 42 bytes
file : loc.nx2
loc.nx2 is up to date.
handleAction(UP_TO_DATE) - 58 bytes
file : projectiles.nx2
projectiles.nx2 is up to date.
handleAction(UP_TO_DATE) - 46 bytes
file : units.nx2
units.nx2 is up to date.
Updates applied successfully.
writeToServer(GET_FILES_TO_UPDATE, [coop])
handleAction(LIST_FILES_TO_UP) - 74 bytes
Files to update: [init_coop.lua]
writeToServer(UPDATE, [bin, init_coop.lua, 589bc2dd251f0523cda2346d5521ab2c])
handleAction(SEND_PATCH_URL) - 240 bytes
TIMEOUT: UpdaterTimeout(('Connection timed out while waiting for data.',))
Disconnected from server at 2015-08-13 22:59:49

I really hope this helps cause I miss playing coop and I know that fixing it has been difficult. Thanks Again, ill see you on FAF.

-Redfox out

**Comment by Sheeo** [comment]
Clear your gamedata -- your client has a shortcut for doing this in the tooltip menu.

**Comment by Redfox442** [comment]
Thank you
