### ISSUE TITLE
Browsing Replay Vault

### ISSUE THREAD

**Issue by Benikens** [FAForever/client#227]
Sorry if this is already reported I thought I saw something on it but I couldn't find it just now. I opened replay vault, clicked in the player search box and started typing then this popped up.

**FAF Username:** benikenslaptop

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** D:\Program Files (x86)\Steam\steamapps\common\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\Benjamin\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "downloadManager\__init__.pyc", line 76, in finishedDownload
RuntimeError: wrapped C/C++ object of type ReplayItem has been deleted

}}}

**Comment by arkitect-dev** [comment]
closing this as major client update should have sorted it, can reopen if if we get more reports for it since major update
