### ISSUE TITLE
Coop lobby crashes when selecting the options.

### ISSUE THREAD

**Issue by T3hFyrefly** [FAForever/client#230]
Not exactly sure what patch this started happening. But it started doing this a few days after Coop started "working" again. I can't change the game settings like difficulty, or popcap as trying to open the menu crashes the game.

This is the error report:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x00938ac8
    attempted to read memory at 0x00000000
 
Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /ratingcolor 00000000 /numgames 0 /mean 1500.0 /deviation 500.0 /country /init init_coop.lua /savereplay gpgnet://localhost/3793150/Fyre-Fly.SCFAreplay /nobugreport /gpgnet 127.0.0.1:60049
 
Callstack:
        Unknown symbol (address 0x00938ac8)
        Unknown symbol (address 0x00914412)
        Unknown symbol (address 0x10e9783b)
 
Last 100 lines of log...
 
debug: Loading module '\000/lua/ui/lobby/data/playerdata.lua\000'
info: Hooked /lua/ui/lobby/data/playerdata.lua with /mods/coop/hook/lua/ui/lobby/data/playerdata.lua
debug: Loading module '\000/lua/ui/lobby/data/watchedvalue/watchedvaluetable.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/watchedvalue/watchedvalue.lua\000'
debug: Loading module '\000/lua/factions.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/gamedata.lua\000'
debug: Loading module '\000/lua/ui/lobby/data/watchedvalue/watchedvaluearray.lua\000'
debug: Loading module '\000/lua/ui/controls/togglebutton.lua\000'
debug: Loading module '\000/lua/ui/lobby/lobbycomm.lua\000'
info: Hooked /lua/ui/lobby/lobbycomm.lua with /mods/coop/hook/lua/ui/lobby/lobbycomm.lua
debug: Loading module '\000/lua/mods.lua\000'
debug: Loading module '\000/lua/system/setutils.lua\000'
debug: Loading module '\000/lua/ui/controls/textarea.lua\000'
debug: Loading module '\000/lua/ui/lobby/trueskill.lua\000'
debug: Loading module '\000/etc/faf/blacklist.lua\000'
debug: Loading module '\000/lua/ui/help/tooltips-country.lua\000'
debug: Loading module '\000/lua/system/dkson.lua\000'
debug: Loading module '\000/lua/ui/lobby/lobbyoptions.lua\000'
info: Hooked /lua/ui/lobby/lobbyoptions.lua with /mods/coop/hook/lua/ui/lobby/lobbyoptions.lua
debug: Loading module '\000/lua/gamecolors.lua\000'
info: /country
info: /init
info: /ratingcolor
info: /numgames
info: /mean
info: /clan
info: /deviation
info: GPGNET: setting nat handler to 0x114e6004
info: LOBBY: Game port 6112[UDP] opened.
info: LOBBY: starting with local uid of 122628 [Fyre-Fly]
info: GPGNET: entering lobby state.
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
warning: {
warning: }
warning: {
warning: }
warning: {
warning:     MEAN = 1500
warning:     StartSpot = 1
warning:     ArmyColor = 17
warning:     PlayerClan = ""
warning:     NG = 0
warning:     Team = 1
warning:     Ready = false
warning:     PlayerColor = 17
warning:     Country = "world"
warning:     PlayerName = "Fyre-Fly"
warning:     AIPersonality = ""
warning:     ObserverListIndex = -1
warning:     BadMap = false
warning:     Civilian = false
warning:     Faction = 2
warning:     OwnerID = "122628"
warning:     RC = "00000000"
warning:     PL = 0
warning:     DEV = 500
warning:     Human = true
warning: }
info: SetGameOption(key="UnitCap",val="1500")
info: SetGameOption(key="ShareUnitCap",val="none")
info: SetGameOption(key="FogOfWar",val="explored")
info: SetGameOption(key="Victory",val="sandbox")
info: SetGameOption(key="Timeouts",val="-1")
info: SetGameOption(key="GameSpeed",val="adjustable")
info: SetGameOption(key="AllowObservers",val=false)
info: SetGameOption(key="CheatsEnabled",val="false")
info: SetGameOption(key="CivilianAlliance",val="enemy")
info: SetGameOption(key="PrebuiltUnits",val="Off")
info: SetGameOption(key="NoRushOption",val="Off")
info: SetGameOption(key="RandomMap",val="Off")
info: SetGameOption(key="Score",val="yes")
info: SetGameOption(key="Share",val="no")
info: SetGameOption(key="Difficulty",val=1)
info: SetGameOption(key="TeamSpawn",val="fixed")
info: SetGameOption(key="TeamLock",val="locked")
info: SetGameOption(key="AutoTeams",val="none")
info: SetGameOption(key="ScenarioFile",val="/maps/x1ca_coop_003.v0005/x1ca_coop_003_scenario.lua")
debug: Loading module '\000/lua/maui/effecthelpers.lua\000'
debug: Loading module '\000/lua/ui/controls/combo.lua\000'
debug: Loading module '\000/lua/maui/statusbar.lua\000'
debug: Loading module '\000/lua/ui/controls/columnlayout.lua\000'
debug: Loading module '\000/lua/ui/lobby/changelog.lua\000'
debug: Loading module '\000/lua/ui/lobby/aitypes.lua\000'
debug: Loading module '\000/lua/ai/customais_v2/sorianai.lua\000'
info: GPGNET: received nat packet from 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
info: GPGNET: sending nat packet to 37.58.123.2:30351
debug: Loading module '\000/lua/ui/dialogs/mapselect.lua\000'
info: Hooked /lua/ui/dialogs/mapselect.lua with /mods/coop/hook/lua/ui/dialogs/mapselect.lua
debug: Loading module '\000/lua/ui/menus/main.lua\000'
debug: Loading module '\000/lua/maui/movie.lua\000'
debug: Loading module '\000/lua/ui/lobby/modsmanager.lua\000'

If I go into the standard lobby for regular MP games I can open the options menu fine. I tried reinstalling the FAFforever client, removing all custom maps and mods, as well as verifying my Game Files to no luck.

I am on Windows 10

**Comment by beeofdoom** [comment]
Also seeing this on Windows 7, brand new installation/new user.

**Comment by Sheeo** [comment]
Wrong repository, apologies for not seeing this until now.

This should be fixed, if not -- report it here: https://github.com/FAForever/fa/issues/new
