### ISSUE TITLE
Notify players when their game is full if they are alt-tabbed.

### ISSUE THREAD

**Issue by julesjacobs** [FAForever/client#233]

**Comment by theeggroll** [comment]
Put fa in windowed mode, you hear "Group Formed" even when alt tabbed.

**Comment by IDragonfire** [comment]
If @Sheeo allow it I can use the notification system for this ;)

**Comment by Sheeo** [comment]
You don't need permission to make pull requests :)

**Comment by IDragonfire** [comment]
I know, but maybe you want a different solution ;)

**Comment by IDragonfire** [comment]
![image](https://cloud.githubusercontent.com/assets/1217999/10835468/1be06d2e-7ea3-11e5-966f-92e7828d4816.png)

**Comment by arkitect-dev** [comment]
what happened with this? did this get PR'd at some point?

**Comment by IDragonfire** [comment]
Personal I stopped the client development. You can continue it ;)

**Comment by Wesmania** [comment]
The PR branch for this is still hanging around in the repo - is it still of any use? Can we rebase or delete it?

**Comment by Wesmania** [comment]
I'll just grab this branch for myself and remove it from upstream, then.

**Comment by ghost** [comment]
This should be closed no ? 
https://github.com/FAForever/client/pull/869

**Comment by Wesmania** [comment]
Yup.
