### ISSUE TITLE
Crash: Ladder maps presentations

### ISSUE THREAD

**Issue by MarcSeebold** [FAForever/client#237]
What i did: Tutorials -> Ladder maps presentations -> Double clicked on map "Eye of the storm"

**FAF Username:** maehze
**FAF Version:** 0.10.125
**FAF Directory:** C:\ProgramData\FAForever
**FA Path:** G:\Steam\steamapps\common\Supreme Commander Forged Alliance
**Home Directory:** C:\Users\Marc\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "tutorials\_tutorialswidget.pyc", line 59, in finishReplay
  File "fa\exe.pyc", line 169, in replay
KeyError: 'uid'
}}}

**Comment by Sheeo** [comment]
The replay was corrupted, I've removed the tutorial from the section for now. Thank you for the report.

Since ladder maps are changing more often, we need a more generalized vault and tutorials for these.
