### ISSUE TITLE
Replay vault results list resets

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/client#239]
This is more an annoying behaviour than a real bug: if u search for a players replays and then switch the tab and switch back, the players name is still in the options field but the list is reseted to default, so u have to search again.

**Comment by arkitect-dev** [comment]
I'd actually class this as a bug in that you lose state on the results list

**Comment by GrotheFAF** [comment]
that is fixed/featured. please close this

**Comment by Wesmania** [comment]
Closing, if happens again, reopen.
