### ISSUE TITLE
nukes disappearing on launch

### ISSUE THREAD

**Issue by irswat** [FAForever/client#249]
have a replay with two nukes fired at the same time. the silos opened but no missiles came out but the missile was subtracted from the silo. I believe they were targeting a unit that died and switched teams after the launch command was issued. full share was on

**Comment by IDragonfire** [comment]
@irswat Thanks for report ;)
1. This is the repository for the client (with news, vault, tournament tab, find games tab ...)... not the game: https://github.com/FAForever/fa
2. What replay?

**Comment by irswat** [comment]
Replay desynced. No notice in game of desync.

**Comment by irswat** [comment]
Just noticed this was client. I'm sorry.

**Comment by Sheeo** [comment]
No problem, please use https://github.com/FAForever/fa/issues/new to generate a new ticket on the game repository :+1:
