### ISSUE TITLE
New perlays dont show in online vault

### ISSUE THREAD

**Issue by nrader** [FAForever/client#258]
**FAF Username:** nrader

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Games\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\root\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

That what happens when i trying to start to view some new replays(the last working ones was around day ago(i tried to watch the ladder ones)). Plus they dont snow up itself until i press "search" without any arguments.
Also if i try to download them first, they doestn't download via browser, while the working ones  can be downloaded via browser, too.

**FAF Username:** nrader

**FAF Version:** 0.10.125

**FAF Directory:** C:\ProgramData\FAForever

**FA Path:** C:\Games\Supreme Commander Forged Alliance

**Home Directory:** C:\Users\root\Documents

**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 125, in onlineTreeClicked
AttributeError: 'QTreeWidgetItem' object has no attribute 'pressed'

}}}

and this happens when i right-clicking at replay folder in the FAF (i mean the one with yyyy-mm-dd and replays writed in the title)

**Comment by Sheeo** [comment]
This was a problem with the livereplay server yesterday, it should be fixed.

Please report if it happens again, thanks!
