### ISSUE TITLE
Fix spoiler free option not being respected in replay vault

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#266]

**Comment by TimWolters** [comment]
I was doing some work on this and I have the main issue fixed. But I can't seem to get an handler on the spoilercheckbox. Any help on this would be welcome as I am not experienced in Python or PyQt and I'm not getting any wiser on the documentation of PyQt.

**Comment by yorick-ne** [comment]
In general it should be possible to use `self.parent.spoilerCheckBox.connect(your_functionname)` somewhere in the `__init__` code with your_functionname being a function that expects 1 parameter for the current state of the checkbox, if i see this right
also if you get an handler for the checkbox, this https://github.com/FAForever/client/blob/develop/src/replays/replayitem.py#L189 can be stored in a dedicated variable ( wouldnt change behaviour, but might make for some cleaner code)
