### ISSUE TITLE
Replay vault error

### ISSUE THREAD

**Issue by irswat** [FAForever/client#270]
**Stacktrace:**
{{{
Traceback (most recent call last):
  File "replays\_replayswidget.pyc", line 121, in finishRequest
  File "fa\exe.pyc", line 150, in replay
  File "json\__init__.pyc", line 338, in loads
  File "json\decoder.pyc", line 365, in decode
  File "json\decoder.pyc", line 383, in raw_decode
ValueError: No JSON object could be decoded

}}}

**Comment by HardlySoftly** [comment]
Related to: https://github.com/FAForever/client/issues/78 https://github.com/FAForever/client/issues/96 https://github.com/FAForever/client/issues/121 https://github.com/FAForever/client/issues/179 https://github.com/FAForever/client/issues/218 https://github.com/FAForever/client/issues/231 https://github.com/FAForever/client/issues/258

Suggest we merge some of these?

Easy to reproduce, occurs whenever the client tries to open a replay from the online vault for a game that is in fact still in progress (try opening the top result whenever you load Online Vault).

Fix for the client side error here I think: https://github.com/FAForever/client/pull/89

Server shouldn't be listing live games when the client requests replays for the online vault tab though.

**Comment by HardlySoftly** [comment]
Can confirm that the dev client correctly handles this situation.

**Comment by irswat** [comment]
Am I incorrect that in the past it was possible to stream games still in progress?

**Comment by HardlySoftly** [comment]
Nope, it is possible to stream games but only from the livestreams tab.

You're right to report this, its a bug and we haven't got around to fixing it properly yet :)

**Comment by HardlySoftly** [comment]
This is a server-side problem only now, so I'm closing it.
