### ISSUE TITLE
Add Challenge feature

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#272]
[BC]Blackheart: right click player -> challenge -> ladder match starts with that opponent

(probably requiring permission from the other end... or maybe it would be better without?)

**Comment by TimWolters** [comment]
I have been thinking about this but it seems really easy to abuse this. Point is that you can easily boosts your rating vs a player you know you can beat.

**Comment by Wesmania** [comment]
I'll consider this abandoned, haven't seen anyone ask for this feature.
