### ISSUE TITLE
Suggestion: Search via ladder rating

### ISSUE THREAD

**Issue by Sovietpride** [FAForever/client#273]
AFAIK,  searching the replay vault at the moment only allows a discriminator of global rating, as opposed to ladder rating. 

If I am wrong, how do I search via ladder rating
IF i am right, is it possible for this to be added?

**Comment by JaggedAppliance** [comment]
When searching the vault now ladder games use ladder rating to display games when searching by rating.

**Comment by Wesmania** [comment]
Considering this abandoned.
