### ISSUE TITLE
Suggestion: Select a subset of the factions when searching for  ladder game

### ISSUE THREAD

**Issue by yorick-ne** [FAForever/client#284]
Currently the Ladder Buttons behave like radiobuttons, i'd suggest to change the behavior analog to the one of checkboxes. With this you could search as UEF and Cybran at once for example.
This would proably need server side support.

**Comment by Sheeo** [comment]
Sounds a lot better than a "Random but not UEF" button, which I've heard a bit about :+1: :)

**Comment by arkitect-dev** [comment]
closing as duplicate
