### ISSUE TITLE
Reenable and rename the "choose maps" button.

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#290]
Like the title says, renaming the button to "show the current rotation" and doing that would be great.
Also possibly a notification if you start searching for the first time after the rotation changed e.g "the rotation changed since you played last, do you want to view it or keep searching y/n"

**Comment by yorick-ne** [comment]
I can have a go at this.
What is the intended behaviour here ? Some button either in the play tab next to all the ladder stuff or somewhere in the mapvault that opens a new window showing the maps ? I could also imagine having this as a seperate tab in the vault, but that would possibly make the ui less user friendly.

**Comment by Crotalus** [comment]
I would vote for a button / icon near the ladder stuff in Play which shows a dialog or panel with the maps.

**Comment by Wesmania** [comment]
"Retroactive" duplicate of #889.
