### ISSUE TITLE
URLs crash chat

### ISSUE THREAD

**Issue by MattDeering** [FAForever/client#315]
As Posted by BH on the forum
https://en.m.wikipedia.org/wiki/Gelfond–93Schneider_theorem

crashes aeolus

<RaptorJesus> !google (ง ͠° ͜ʖ ͡°)ง ᴡᴀʀɴɪɴɢ, ᴅᴏᴏᴋs ʀᴀɪsᴇᴅ (ง ͠° ͜ʖ ͡°)ง
<QAI> http://lmgtfy.com/?q=(ง+͠°+͜ʖ+͡°)ง+ᴡᴀʀɴɪɴɢ,+ᴅᴏᴏᴋs+ʀᴀɪsᴇᴅ+(ง+͠°+͜ʖ+͡°)ง

this also crashed aeolus. Attempting to paste these into pm blew up before when pasted. Logs attached

[forever - Copy.txt](https://github.com/FAForever/client/files/170251/forever.-.Copy.txt)

**Comment by Sheeo** [comment]
Fixed by 926133f9e599a269b39dc5ac4e0b5daae6d48f97
