### ISSUE TITLE
Replayvault not showing WIN LOSE correctly

### ISSUE THREAD

**Issue by TimWolters** [FAForever/client#316]
In the replayvault with the spoilercheckbox off it displays that in official one vs one's both player win. Looking from the incoming JSON both players are in the same team. Comments within the code suggest that if players are in team 1 the game is FFA but I'm not sure of that.

If above is true this means if all players are in team 1, the player with the highest score is the winner and there shouldn't be a team displayed.

Referencing:

http://forums.faforever.com/viewtopic.php?f=3&t=11858

**Comment by arkitect-dev** [comment]
it is also showing both players lose or some replays

4610628 shows both lose but in two columns
4610360 shows both win in one column

**Comment by TimWolters** [comment]
Looking back on this, It's probably something to do with FFA and how the 1 vs 1 mod handles teams. I've once made a thread [here](http://forums.faforever.com/viewtopic.php?f=3&t=11858) but I'm not really sure how it should work. If I knew I would certainly update it with my current pull request for the replayvault.

**Comment by Sheeo** [comment]
Sorry for not replying on this -- yes, the 1v1 games are handled serverside by stuffing both players into team 1. This is the 'ffa team' as defined by the game, so the client should handle players allocated to this team as being FFA players.

**Comment by arkitect-dev** [comment]
@Sheeo  is it clear what changes need to happen to fix this? would you be able to give tim a couple of pointers on what he should do?

**Comment by TimWolters** [comment]
I got it, but thank you arkitect

**Comment by arkitect-dev** [comment]
great, I'm pushing for all issues to be in an actionable state - i.e. finding necessary info or  ready for dev, so if there are issues that look to not have a clear direction (like this one didn't) i'll try and chase them up
