### ISSUE TITLE
Avatars cannot be removed from users

### ISSUE THREAD

**Issue by arkitect-dev** [FAForever/client#323]
you bring up a screen of all the avatars and you click on the one you want to remove from someone
it shows you who has it, and you can tick boxes and click " remove selected"
but clicking the avatars does nothing now

**Comment by speed2CZ** [comment]
log https://gist.github.com/speed2CZ/424629b003b3d0ba54f23949947084bf

**Comment by HardlySoftly** [comment]
It'll probably break in another way after the server starts handling those list_avatar_users messages, but we can cross that bridge when we come to it.

**Comment by duk3luk3** [comment]
This is currently not part of the API, so can't be fixed for now.

**Comment by Wesmania** [comment]
Should be fixed by the avatar manager (Jeremy).
