### ISSUE TITLE
Win ratio dropping regardless of winning/losing/drawing ladder game

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/client#326]
[game.zip](https://github.com/FAForever/client/files/202801/game.zip)
[forever.zip](https://github.com/FAForever/client/files/202807/forever.zip)

It's counted as a loss for the winratio.
It's just going down and down ( Saw this for a lot of people.

**Comment by HardlySoftly** [comment]
Not sure why this is a client bug, the leaderboards are just a webpage hosted by the server.

**Comment by GrotheFAF** [comment]
this is a server bug. (wins are not counted since the feb 2016 update)
so this should be closed.

**Comment by Wesmania** [comment]
Agreed.
