### ISSUE TITLE
Unused requirement

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#337]
Is it known why "lupa" is listed in requirements.txt?

It seems to have been introduced here: https://github.com/FAForever/client/commit/cce6ecee1ac38519fe6ba7c21157581db20a97f2

**Comment by Sheeo** [comment]
It's there to replace the lua data parser the client currently has.

Alternative is to move that into faftools as well and use lupa if it's available, but the dataparser otherwise.
