### ISSUE TITLE
Ensure IRC userlist is populated with FAF information

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#341]
Currently if the client manages to connect to IRC before it has authenticated with the server, it doesn't have the list of online users available when the #aeolus userlist is sent, which means everyone shows up as IRC users.

Either we should update IRC user information when receiving `player_info` messages, or (simply) defer connecting to IRC until we're authenticated with the FAF server (I believe this was done in the past?) 

**Acceptance Criteria**
- Users in the chatlist should no longer wrongfully display as IRC users in any case.

**Comment by HardlySoftly** [comment]
If the IRC user information was received first, chatters were initialised with an id of -1, and so weren't correctly updated.
