### ISSUE TITLE
Installer Distfiles problem

### ISSUE THREAD

**Issue by Bigponorks** [FAForever/client#347]
the installer from forged alliance forever website is spit out the cabinet file 'distfiles' required for this installation is corrupt and can not be used.

if u could look into this. it would be lovely

**Comment by Crotalus** [comment]
Try download the client again, sounds like your browser corrupted the installer or similar.

**Comment by Bigponorks** [comment]
ok i can try the internet  explorer cause i use chrome but if it does not work then i will update this

**Comment by Bigponorks** [comment]
internet explore does not work so it firefox time

**Comment by Bigponorks** [comment]
Firefox has no affect on it so i have no idea what is wrong. for a better look at the problem. i may a video so this problem could be view and resolve by the community. https://www.youtube.com/watch?v=92R8I9rjL5E

**Comment by Bigponorks** [comment]
never mind the problem was my bit defender antivirus program

**Comment by arkitect-dev** [comment]
will close this then since it is resolved
