### ISSUE TITLE
Horrible performance in replayswidget

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#351]
Specifically this appears to be a really expensive operation: https://github.com/FAForever/client/blob/develop/src/replays/_replayswidget.py#L441

It gets called for every player in each gameInfo item that the client receives, which on startup incurs can be a lot.

For reference when I tested this line was being called ~1300 times and was adding a startup delay of 11 seconds to the client (more time than everything else put together)

**Comment by Crotalus** [comment]
Should probably use `setUpdatesEnabled(false)`  when batch updating stuff like that, probably same thing when populating nicknames in #aeolus

**Comment by Wesmania** [comment]
Is this still an issue?
