### ISSUE TITLE
Ladder game setup problems

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#359]
Myself and many people i've spoken to have to keep researching the ladder to get a game set up. It regularly hangs on the setting up automatch screen, or the connecting screen, usually on the setting up automatch screen for me. Also not sure what repo this issue should be posted to.

[game.TXT](https://github.com/FAForever/client/files/300869/game.TXT)

**Comment by JaggedAppliance** [comment]
[foreverlog.txt](https://github.com/FAForever/client/files/319467/foreverlog.txt)
[gamelog.txt](https://github.com/FAForever/client/files/319468/gamelog.txt)

Here's more logs from me, i was trying to play with ZLO. We played one game fine then couldn't get a second game to start. I noticed that zlo appeared as in a lobby for the games that didn't start while the client never showed me in those lobbies.

**Comment by zlo-faf** [comment]
[game.txt](https://github.com/FAForever/client/files/319502/game.txt)
[forever.txt](https://github.com/FAForever/client/files/319501/forever.txt)

**Comment by JaggedAppliance** [comment]
We got another game to start after zlo refafed and i noticed i was in the lobby first and zlo joined, perhaps some people have more trouble being the host of a ladder game than joining one?

**Comment by micheljung** [comment]
Some extractions from the logfiles (I'm just trying to help, I'm not going to fix anything):

JaggedAppliance client:

```
2016-06-16 23:43:23,960 INFO     connectivity.helper.ConnectivityHelper Unknown natpacket
```

JaggedAppliance game:

```
info: LOBBY: Connecting to host "ZLO" [Crushinator:62988, uid=145]
info: System: \000Connecting to game host...
```

ZLO client:

```
2016-06-17 03:10:00,694 INFO     client._clientwindow           Outgoing JSON Message: {"args": ["176.61.44.57:50981", "Hello from 118147"], "command": "ProcessNatPacket", "target": "connectivity"}
2016-06-17 03:10:00,694 INFO     connectivity.helper.ConnectivityHelper Unknown natpacket

2016-06-17 03:10:00,756 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "src\fa\game_session.py", line 123, in _peer_bound
AttributeError: 'NoneType' object has no attribute 'send'
```

ZLO game:

```
info: LOBBY: rejecting unexpected connection from ZLO-PC:53023
```

I recommend using a less buggy client ;-)

**Comment by HardlySoftly** [comment]
I already identified where the problem is, see https://github.com/FAForever/client/issues/366

**Comment by Crotalus** [comment]
It's a chain of unfortunate events that causes these problems. Something is running on port 15000 on his machine, blocking the replay server from starting:

```
2016-06-13 10:59:55,216 ERROR    fa.replayserver                cannot listen, port probably used by another application: 15000`
```

The client handles this by hard exit, unfortunately this doesn't happen due to a typo with the exit command

```
2016-06-13 10:59:57,367 ERROR    __main__                       Uncaught exception
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "src/__main__.py", line 103, in <module>
  File "src/__main__.py", line 73, in runFAF
NameError: global name 'exit' is not defined
```

So the second part of setting up the lobby connections will never happen due to the above error.
this code: (https://github.com/FAForever/client/blob/develop/src/client/_clientwindow.py#L811)

**Comment by Crotalus** [comment]
This commit introduced the error
https://github.com/FAForever/client/commit/04d8eb709bd6ffa4f7957caf097a77f09aac8584

PR here:
https://github.com/FAForever/client/issues/381

**Comment by JaggedAppliance** [comment]
Ladder games still sometimes hang on "setting up automatch"

**Comment by duk3luk3** [comment]
So... where are your log files?

**Comment by JaggedAppliance** [comment]
[forever (2).zip](https://github.com/FAForever/client/files/769777/forever.2.zip)

**Comment by JaggedAppliance** [comment]
[forever (3).zip](https://github.com/FAForever/client/files/851275/forever.3.zip)
[game.zip](https://github.com/FAForever/client/files/851283/game.zip)

**Comment by turinturambarfa** [comment]
hope this helps
[logs.ZIP](https://github.com/FAForever/client/files/851540/logs.ZIP)

**Comment by Wesmania** [comment]
Is it still an issue?

**Comment by JaggedAppliance** [comment]
Yes it is.

**Comment by zlo-faf** [comment]
I Guess i should try Downlord's client and report results. Issue became less frequent recently for me, but others still have it (e.g. Oxideion)

**Comment by JaggedAppliance** [comment]
[forever (2).zip](https://github.com/FAForever/client/files/1797764/forever.2.zip)
[game.zip](https://github.com/FAForever/client/files/1797765/game.zip)
More logs

**Comment by PhilipJFryFAF** [comment]
https://pastebin.com/YKmdaKjM
log from some faf user who can't get a ladder game set up 50% of the time (not sure if it's the same issue since he says the game doesn't even start to begin with)

**Comment by Wesmania** [comment]
Can't do anything with this without game.log.
