### ISSUE TITLE
Ladder map known before the game begins

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#360]
You can avoid playing maps you don't like on ladder because the client shows you in a lobby and gives the map name before the game is launched, allowing you to quit with no penalty.

**Comment by GrotheFAF** [comment]
It should be checked if this got even worse with the new map-column in chat. (next client RC)

if so, the map could be withholden for some time for ladder games.

**Comment by GrotheFAF** [comment]
It needs to be tested, if hiding the map and title during game.state = OPEN is enough.
(Because it is possible that during FA launch and ingame start, game.state is already PLAYING and info is revealed with the quit with penalty option)

**Comment by JaggedAppliance** [comment]
The map and the title is hidden until you are "in transit," loading the game. I don't know but I assume quitting at this point would lead to a loss being recorded.

**Comment by GrotheFAF** [comment]
Great. Could you try that - I mean quitting as soon as you can see the map, and check if it is registered as lost. If so, we could finally consider this solved ... and of course ... I'm sorry for your loss ;-)
