### ISSUE TITLE
Client uses hard-coded URLs to find things like the Vaults

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/client#363]
This makes testing stuff on the dev server much harder. We have the ability to force development environment in the init file. I'd like that toggle to also change content.faforever.com references to content.test.faforever.com, throughout the code.

**Comment by HardlySoftly** [comment]
Some hardcoded urls outside the config files:

https://github.com/FAForever/client/blob/develop/src/chat/chatter.py#L300
https://github.com/FAForever/client/blob/develop/src/chat/chatter.py#L302
https://github.com/FAForever/client/blob/develop/src/client/_clientwindow.py#L523
https://github.com/FAForever/client/blob/develop/src/client/_clientwindow.py#L1178
https://github.com/FAForever/client/blob/develop/src/downloadManager/__init__.py#L11
https://github.com/FAForever/client/blob/develop/src/fa/maps.py#L20
https://github.com/FAForever/client/blob/develop/src/fa/maps.py#L21
https://github.com/FAForever/client/blob/develop/src/fa/maps.py#L22
https://github.com/FAForever/client/blob/develop/src/replays/replayitem.py#L97
https://github.com/FAForever/client/blob/develop/src/stats/_statswidget.py#L219
https://github.com/FAForever/client/blob/develop/src/tutorials/tutorialitem.py#L93
https://github.com/FAForever/client/blob/develop/src/util/__init__.py#L15
https://github.com/FAForever/client/blob/develop/src/util/crash.py#L37
https://github.com/FAForever/client/blob/develop/src/vault/__init__.py#L59

If someone feels like cleaning these up that would be awesome

**Comment by aeoncleanse** [comment]
Yes, this is my plan for tomorrow. @ChrisKitching is (fingers crossed) going to give me some pointers, and I'm hoping @micheljung and yourself might help too, if I need it. Probably will need to set up client testing to test it out. 

This is my plan so far: https://github.com/aeoncleanse/client/commit/2382aac8dbdfcd455fdf62eb0275acc3b0c98b4a
