### ISSUE TITLE
Ladder rating (shown) in replays stays the same until refaf

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#371]
It happens often that the ladder rating shown in game or in replays doesn't update for several games in a row.
examples:
4831570, 4831829, 4832282, 4832516
4845812, 4845874, 4845942

**Comment by madformuse** [comment]
Hi Grothe It's because you're not getting better :)

**Comment by GrotheFAF** [comment]
It seems the first game after faf-start/refaf, game/replay and Leaderboard rating are the same.
(when fa gets the rating from faf then it seems faf doesn't update the (internal) rating from start/logon.
when fa got it's rating from the server, then it's the user-logged-on-rating which isn't updated after logon)
So there seems to be a logon-rating somewhere that isn't updated after logon.

**Comment by GrotheFAF** [comment]
fixed with a server update (some time ago)
