### ISSUE TITLE
Chat Lobby - user status shows in long gone games ->  FAForever/server#142

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#373]
example: Zock is shown in game 4815741 from the 2016-06-04 on the 2016-06-16 (now). 
somethings up with that game in Replays: it shows duration 09:42:18, while replayparser shows runtime 0:19:05.

Seen it a couple of times happening to other players.

**Comment by HardlySoftly** [comment]
This is actually a server issue, check the related server issue here: https://github.com/FAForever/server/issues/142

Thanks for making the bug report though, keep it up :)
