### ISSUE TITLE
Using /me sometimes places name across multiple lines

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#379]
I think this is something to do with the underlying QTextEdit insertHtml method, where applying italics to the text makes it longer than it expected (so the name doesn't fit).

A name that is longer works fine, a name that is shorter works fine, and removing italics makes it work as well.

**Comment by HardlySoftly** [comment]
Changing the text wrap mode seems to affect things, but not in the ways we want.

Looking for suggestions on this :)

**Comment by Sheeo** [comment]
Styling issue -- adjust the width of the container in the [stylesheet](https://github.com/FAForever/client/blob/develop/res/client/client.css)

**Comment by HardlySoftly** [comment]
Wouldn't this just mean different length names are affected?

**Comment by Sheeo** [comment]
Depends on how you adjust the style.

**Comment by yorick-ne** [comment]
Setting this https://github.com/FAForever/client/blob/develop/src/chat/channel.py#L67 to a higher value should fix this. It is the width of the clantag + name ( i guess in pixels ? ).
How long can a name in FAF possibly be ?

**Comment by HardlySoftly** [comment]
Again, this would just push the problem to people with longer names, while also changing the aesthetic of chat.

**Comment by Wesmania** [comment]
Is it still an issue?

**Comment by Wesmania** [comment]
I'll close it due to inactivity.
