### ISSUE TITLE
Medicraze issues again. it happens every time...ladder

### ISSUE THREAD

**Issue by Medicraze** [FAForever/client#380]
[uid.txt](https://github.com/FAForever/client/files/330796/uid.txt)
[forever.txt](https://github.com/FAForever/client/files/330797/forever.txt)
 ok so this has been happening for like 3 weeks...

I really would love for ladder to start working :(

thanks for any help

**Comment by HardlySoftly** [comment]
Duplicate of https://github.com/FAForever/client/issues/366

There's a server issue open for this too (https://github.com/FAForever/server/issues/162), has anyone got a status update for this?

**Comment by Medicraze** [comment]
I'd love to find out how i can fix this...

**Comment by micheljung** [comment]
Duplicate of #359
