### ISSUE TITLE
Absolute file paths get put into logs

### ISSUE THREAD

**Issue by HardlySoftly** [FAForever/client#388]
Some privacy concerns here if we're encouraging people to share logs

**Comment by ghost** [comment]
Should we not put the absolute path files in logs then ?

But then it can make debugging harder in some scenario harder because we don't have the path.
I don't think it is a good idea to remove them (this issue should be closed unless you really want to hide absolute file paths in logs...).

**Comment by Wesmania** [comment]
I'll consider this abandoned for now, reopen if it's still an issue.
