### ISSUE TITLE
Replays not showing up in the vault

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#396]
I've played some maps that were uploaded since map upload returned and the replays for these matches are not in the vault.
IDs: 5026288, 5027600, 5027622
[logs.zip](https://github.com/FAForever/client/files/409268/logs.zip)

**Comment by GrotheFAF** [comment]
the replay are in the vault...
http://fafafaf.bitbucket.org/#5026288 , http://fafafaf.bitbucket.org/#5027600 , http://fafafaf.bitbucket.org/#5027622 (8.8.-9.8.2016)
The maps seems unknown, even though the maps are in map vault.
Asuming that this were (mod:) faf games .. the server don't deliver them in a Replay ({name},faf) search.

**Comment by JaggedAppliance** [comment]
I can't find any Dusty mounds games in the vault. 5159390 didn't show up in the vault

**Comment by Wesmania** [comment]
I'll consider this abandoned for now, reopen if it's still an issue.
