### ISSUE TITLE
Some Maps have preview images that are to big

### ISSUE THREAD

**Issue by yorick-ne** [FAForever/client#407]
Noticed this for 12_the_pass_v6_wv13.v0006 and some other maps. The preview image has size 128x128, the normal size is 100x100.
This causes them to be not displayed correctly, in this client at least.

**Comment by GrotheFAF** [comment]
I solved this .. for the display part in 'Play'.  
fixed in https://github.com/GrotheFAF/client/commit/ea8df3d3bdcb65cfe82b54d50d3fc775d676ea78

**Comment by GrotheFAF** [comment]
you can close this, I guess
