### ISSUE TITLE
Crash with surround audio setup

### ISSUE THREAD

**Issue by Uveso** [FAForever/client#408]
Is it possible to get the Windows speaker configuration and display a warning when `Stereo` is not set as default ?

**Comment by aeoncleanse** [comment]
It just spams your log. Extremely irritating, I wish we could just alter the binary to get rid of the stupid warning.

**Comment by GrotheFAF** [comment]
I also get a crash report at the end of each game (since a while) with my 4 speaker setup.

**Comment by Uveso** [comment]
hi grothe
do you mean with crash report an EXCEPTION_ACCESS_VIOLATION?
If yes can you post the Crash address ?

**Comment by GrotheFAF** [comment]
I don't get the crash message when I close FA from a replay.
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at address 0x009d7b75
https://github.com/FAForever/fa/files/451572/FA-crash_report.txt

**Comment by Uveso** [comment]
Grothe please add your comment here:
https://github.com/FAForever/fa/issues/1467

I am collecting all errorr related to `EXCEPTION_ACCESS_VIOLATION at address 0x009d7b75` there.

**Comment by Wesmania** [comment]
This is a game issue, not a lobby issue.
