### ISSUE TITLE
working on Replay.ui - refine on 'Redesign UI in replay vault'

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#409]
I'm working on:
- making it look nicer.
- fix some errors.
- make it work for more mods.

based on 'TimWolters committed with Crotalus on 17 Jul':
https://github.com/FAForever/client/commit/c90fc1351b617bbfe5ad51bdc0210cfbbf1cc222

**Comment by TimWolters** [comment]
I'm not feeling really well at the moment but if you need something from me. Just let me know.

**Comment by GrotheFAF** [comment]
Hi  @TimWolters , ok... questions:
why did you exclude team=0 ('if team:'  in def infoPlayers)?  (some (rare) replays come with team 0)
I can't seems to find where the replays are actually read, any hint? (start,end duration are often wrong)

**Comment by TimWolters** [comment]
Hey Grothe, the exlusion of team=0 was already in the code and I did not change it.
You could find the json of the replays in self.replayinfos. Where this is actually recieved from the server. I forgot.

**Comment by TimWolters** [comment]
For the team=0. it was originally in the code so I did not change it. I have no idea what is exactly stands for so I left it in.
I haven't looked at the code for a while so i'm not really that sure. Most of it is handled within replaywidget and replayItem (obviously). The html is created in generateInfoPlayersHtml. The html of it is stored in the variables you see on top. If you want to know what is send from the server. I would look at replaywidget.recievedJSON as the message is recieved there. Also the json is stored in self.replayInfos.

**Comment by GrotheFAF** [comment]
thx .. allready done... and in pull. https://github.com/FAForever/client/pull/411
