### ISSUE TITLE
search replays by player

### ISSUE THREAD

**Issue by tobias-strenger** [FAForever/client#414]
when u search replays by player and switch back and forth to the replay tab, the name of player remains in the search field, but the replays are reloaded and not specified anymore

**Comment by GrotheFAF** [comment]
it goes back to automatic mode (recent replays). I find that annoying too.
if you stop that behavior after a search, the question is how do you get back to automatic mode .. maybe clear all search fields?

**Comment by GrotheFAF** [comment]
I added a checkbox where one can disable the automatic reload. (commit to come)

**Comment by tobias-strenger** [comment]
also if you choose the options "view replays in vault". The client switches to the online vault tab, if this tab is active. If not, u see the wrong tab opened.

**Comment by GrotheFAF** [comment]
Check box 'Keep Search' in https://github.com/GrotheFAF/client/commit/481cd1755427041b0f47c3e9a5d93998013e1e99 + https://github.com/GrotheFAF/client/commit/f3545330f1f15d891655af38ef72b253d30fe05d
Fix switch to Online Vault in https://github.com/GrotheFAF/client/commit/b5e1b35ac08d909e9ba34dbc9ef31702a789234b

**Comment by duk3luk3** [comment]
Closed with #496 and #498
