### ISSUE TITLE
remember me feature and autologin on client

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/client#416]
soooooooooooooooo by some absurd accident i got logged out of the client, and then the autologin featured got disabled - now i need to press the login button every time on startup.
http://puu.sh/rm5ge/7016094a63.jpg
so now this screen pops up every time. i dont need to type in my user/pass but i do need to press the button, which didnt happen before. i suspect its something related to how i remember there being a "log me in automatically" box as well which is not here anymore. perhaps.

**Comment by duk3luk3** [comment]
Can't reproduce this atm - I just get logged in automatically. Is this still an issue?

**Comment by Exotic-Retard** [comment]
for some reason it went away by itself
i guess we can close this for now
