### ISSUE TITLE
Replays not showing up in vault on map Dusty Mounds

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#420]
[logs(1).zip](https://github.com/FAForever/client/files/496037/logs.1.zip)
I've played some maps that were uploaded since map upload returned and the replays for these matches are not in the vault.
IDs: 5026288, 5027600, 5027622
Possibly related: https://github.com/FAForever/server/issues/207

**Comment by CookieNoob** [comment]
I would say it is related to something completely different... https://github.com/FAForever/replay-server/issues/2

**Comment by CookieNoob** [comment]
This doesnt affect only Dusty Mounds, it also affects ALL ultimate maps. And also some other maps as well (i.e. Anchor).

**Comment by JaggedAppliance** [comment]
Yeah Farce also doesn't show up, seems like maybe all new maps don't show up?

**Comment by CookieNoob** [comment]
new maps show up, as long as there isnt a second version uploaded. I.e. if you upload your map (v0001) and then realize there is a bug/mex not buildable/whatever and directly upload a corrected version (v0002), all games on that new version wont be shown. Since no one (almost) downloaded the old version though, you wont see any games at all in the replay vault.

**Comment by HardlySoftly** [comment]
Yeah, this isn't a client bug, just the server code not being very smart.

https://github.com/FAForever/legacy-secondaryServer/blob/master/replays/replayServerThread.py#L603

Can close this issue I guess.

**Comment by Brutus5000** [comment]
Should be fixed with FAForever/legacy-secondaryServer#1

**Comment by duk3luk3** [comment]
Can someone confirm that? @CookieNoob

**Comment by CookieNoob** [comment]
yes higher map versions show up in the search now. Really awesome @Brutus5000! thx very much :)

(I guarantee you that all mappers are really happy now)
