### ISSUE TITLE
games hosted by friends are not set to the top of the list in find games

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/client#421]
pretty ancient issue, but this is yet another functionality that got lost over time.

if you have someone friended, they used to appear as friend colour and at the top of the list. now this is no longer the case. pretty self explanatory i guess

**Comment by Wesmania** [comment]
Which 'find games' screen does this refer to?

**Comment by Exotic-Retard** [comment]
its called the play tab now. and i think that in the year or so since this was put up, it appears to have been fixed somewhere along the way, so yeah. good stuff. closing.
