### ISSUE TITLE
Maps being downloaded into wrong folder for user with special characters

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/client#428]
We have this in the init file

``` LUA
-- these are the classic supcom directories. They don't work with accents or other foreign characters in usernames
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods', '/mods')
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\maps', '/maps')

-- these are the local FAF directories. The My Games ones are only there for people with usernames that don't work in the uppder ones.
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods', '/mods')
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\maps', '/maps')
```

to load maps from ProgramData folder if the user has some special characters in the default user name since the game doesn't handle it (for example russian characters Документы, etc ...)

But when those people are downloading maps it downloads them into MyDocuments and then the game can't load it and they'll get the error that they're missing the map.

If they move the map file manually into the folder in ProgramData, it works.

**Comment by heelix** [comment]
Is there an easy way we could get a test user created for this? (Without creating a new email address for it)

**Comment by duk3luk3** [comment]
What does this work out to? `C:\ProgramData\FAForever\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods`?

**Comment by duk3luk3** [comment]
We actually already try to detect this in [`src/util/__init__.py`](https://github.com/FAForever/client/blob/develop/src/util/__init__.py#L93-L97):

``` python
PERSONAL_DIR = str(QDesktopServices.storageLocation(QDesktopServices.DocumentsLocation))
try:
    getpass.getuser().decode('ascii')  # Try to see if the user has a wacky username
except:
    PERSONAL_DIR = os.path.join(APPDATA_DIR, "user")
```

So we probably need a better "wacky username" check; maybe also add a "wacky locale / codepage" check. I believe that `string.decode('ascii')` basically only checks whether there are any characters > 127.

Also, why does it set `PERSONAL_DIR` to `QDesktopServices.storageLocation(QDesktopServices.DocumentsLocation)` but then checks `getpass.getuser()`?

**Comment by duk3luk3** [comment]
Someone who has this bug needs to install and run the client from https://ci.appveyor.com/project/Sheeo/client/build/866/artifacts and then upload forever.log.

**Comment by duk3luk3** [comment]
Oh btw @heelix you don't need a testaccount for this, just make a new windows user with a "weird" name and install and run faf with that user. It's a windows username problem, not faf username

**Comment by duk3luk3** [comment]
I r gud programmer

```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "src/__main__.py", line 40, in <module>
  File "src\util\__init__.py", line 96, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)

---------------------------
OK   
---------------------------
```

EDIT: Actually, @muellni r gud programmer, he broke it :-) https://github.com/FAForever/client/blame/a5dd8bfc6db545f1d6a1b2b4491cafd25b994313/src/util/__init__.py#L96
