### ISSUE TITLE
caption of "do you want to download map" window wrong

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/client#442]
![capture](https://cloud.githubusercontent.com/assets/21953792/19830597/6fe2f6e4-9dfb-11e6-8050-825d031071c2.PNG)

should be "map" instead of "mod".
https://github.com/FAForever/fa/issues/1648#issuecomment-257081972

**Comment by GrotheFAF** [comment]
fix in https://github.com/FAForever/client/pull/444
