### ISSUE TITLE
FAForever.exe fails to start

### ISSUE THREAD

**Issue by nyov** [FAForever/client#443]
I'm having a friend who cannot start the current FAF client, freshly installed on Windows 7 (from Forged.Alliance.Forever-0.11.60-win32.msi).

`ImportError: cannot import name RAND_egd`

Since I'm not on Windows I have no clue about this error. Can anyone help?

![faf error](https://cloud.githubusercontent.com/assets/438293/19837462/f41e74e0-9eb1-11e6-8633-794e3ad8f0f5.jpg)

**Comment by nyov** [comment]
Okay from the little I found here on [StackOverflow](https://stackoverflow.com/questions/31762371/importerror-cannot-import-name-rand-egd#answer-32506523), this may be fixable in the build process of `py2exe` by cleaning up the `dist` and `build` directories;
which may remove artifacts left over from building on an older Python version?!

As someone there says:

> This might be caused by old version of socket.pyc.

I have no idea how the windows client package is built, so it may be something else entirely. Just a stab in the dark.

**Comment by micheljung** [comment]
Try https://github.com/FAForever/downlords-faf-client/releases instead

**Comment by nyov** [comment]
@micheljung, can't get it to build on linux, so I won't be.
But I'll tell my friend about your client, perhaps it works for him. Thanks.

**Comment by Sheeo** [comment]
We don't use `py2exe` for building the client, we use `cx_Freeze`. It looks like it could be some conflicting dll's. Are you sure it's a fresh install?

**Comment by nyov** [comment]
Well, it seems another install over it solved the issue. Strange.
An older client wasn't installed though.
It's not my machine so I can't be 100% on that, but that's what I got told.

I'll close this then.
But if [someone](https://forums.faforever.com/viewtopic.php?f=40&t=11992&p=122601&hilit=cannot+import+name+RAND_egd&sid=957a46b6702ce5eb96ab669ad208d237#p122601) [else](https://forums.faforever.com/viewtopic.php?f=3&t=11782&p=120332&hilit=cannot+import+name+RAND_egd&sid=957a46b6702ce5eb96ab669ad208d237#p120332) has this issue, this may be how to solve it (reinstall).
