### ISSUE TITLE
make 'gone offline' Hosts visible in hosted Games in Play 

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#455]
Currently you can't see if a host went offline. (only if you check if host is in chat online)
So more user join and wait  (and evt. leave) -> frutrating waste-o-time.
One could mark or hide the game (so no one else joins)
Automatically pm the joined user about the situation.

First step could be give the Player another color (black/red?) that might not be effectiv for randon color user, so be explizit: '[Player] (offline)'.

**Comment by duk3luk3** [comment]
Please describe:
- What the current behaviour is
- What problem that behaviour causes
- What your proposed fix is
- How your proposed fix solves the problem

**Comment by GrotheFAF** [comment]
I did all that, just read. du torf ;-)
and fix is in PR ... please process....

**Comment by Wesmania** [comment]
I don't understand - we're talking about a situation where somebody is hosting a game, but offline? As in he's hosting the game and then quit FA, and the game stayed behind as a zombie? Isn't it a server bug that needs fixing in that case, not a behaviour we need to plan around?

**Comment by GrotheFAF** [comment]
The user(host) is in FAF but only shown as irc user. (not sure if all user see the user/host only as irc)
And this is just a special (aka visble) case of user in faf only shown as irc.
And yes, it might be a server bug, (like the zombie games https://github.com/FAForever/server/issues/276), but is anybody working on that? So let's try to make the (server) bugs less painfull, shall we?
#HANDYCAPPEDLIVING ;-)
Maybe the code in client/connectivity needs some inspection as well.
