### ISSUE TITLE
Rollback for uid merge needed

### ISSUE THREAD

**Issue by muellni** [FAForever/client#466]
Commit 9d1c3f68c4bea1e8d3184194a5ad3603adeb8912 went wrong and basically reverted `util/__init__.py`.

**Comment by duk3luk3** [comment]
Can you explain that please? What got reverted? the commit you linked looks fine to me...

**Comment by muellni** [comment]
It reverted the changes from 388f642ce425aec49099b06b5e861eeed88fd91d and 7ff9ddd1072924c5877657a1486a06bd35e6d4a1

**Comment by duk3luk3** [comment]
I see. Just make a PR that fixes that? No "rollback" needed.
