### ISSUE TITLE
Make tabs optional

### ISSUE THREAD

**Issue by fafafaf** [FAForever/client#47]
![Optional tabs](https://cloud.githubusercontent.com/assets/8939457/4433882/975fc900-46f4-11e4-93b0-c9e7a2d337f0.png)

**Comment by duk3luk3** [comment]
This issue is now about @Wesmania revamping the client settings interface.

**Comment by Wesmania** [comment]
I'll consider this abandoned, optional tabs are nice but very minor, and we'll have ways to go before we refactor settings.
