### ISSUE TITLE
firewall rules for faf-ice-adapter.exe

### ISSUE THREAD

**Issue by muellni** [FAForever/client#470]
Create Windows firewall rules to allow all incoming connections to faf-ice-adapter.exe during installation

**Comment by muellni** [comment]
I'll resolve this by triggering the firewall dialog on client startup, so it doesn't become hidden behind the game

**Comment by sikoragmbh** [comment]
The client now triggers the `reserveRelays` method, which triggers the firewall dialog after logging in with the client. This should be sufficient.

**Comment by muellni** [comment]
The client now triggers the `reserveRelays` method, which triggers the firewall dialog after logging in with the client. This should be sufficient.
