### ISSUE TITLE
What is needed for python 3 support?

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#474]
* PyQT / QT upgrade?
* any other dependencies we use that aren't python3 compatible?
* our own code?

**Comment by Crotalus** [comment]
Made the client run on 3.5 quite a while ago, so salvaging that code could save some time:
https://github.com/FAForever/client/tree/3.5

**Comment by duk3luk3** [comment]
Fix it up and make it into a PR or find someone else to do it :+1:

**Comment by duk3luk3** [comment]
Current status: https://travis-ci.org/FAForever/client/builds/177770664

I ripped out travis' python3.5 and useless virtualenv.

No idea why pytest errors now, it works perfectly in a fresh ubuntu 14.04.5 VM with identical setup.
