### ISSUE TITLE
Appveyor fails to download qt a lot

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#488]
This happens a lot: https://ci.appveyor.com/project/Sheeo/client/build/902

Need to either retry download or figure out what the problem is (rate-limiting somewhere?)

**Comment by muellni** [comment]
According to https://www.appveyor.com/docs/installed-software/#python there's Miniconda installed, which is a Python distro allowing to install pyqt using `conda install pyqt`. Maybe we could use that...

**Comment by duk3luk3** [comment]
Try it :) All you need to do is change appveyor.yml and push to a branch in this repo.

**Comment by muellni** [comment]
k, I did, and looks like it's working: https://github.com/FAForever/client/pull/493
