### ISSUE TITLE
ICE adapter communication needs revamp

### ISSUE THREAD

**Issue by muellni** [FAForever/client#492]
The communication between the client and the ICE-Adapter uses simple [JSONRCP](http://www.jsonrpc.org/specification). It is done bi-directional, so the client [can send requests to the server](https://github.com/FAForever/ice-adapter#methods-client--faf-ice-adapter) and [the server can send requests to the client](https://github.com/FAForever/ice-adapter#notifications-faf-ice-adapter--client-).
There's a Python library which works: [bjsonrpc](https://github.com/deavid/bjsonrpc). But it didn't work with the Qt mainloop, so a simple replacement was written from scratch: The `connectivity.JsonRpcTcpClient` class.

The `connectivity.JsonRpcTcpClient` class needs to be replaced. Preferably some JSONRPC library, where the transport can be replaced using a `QTcpSocket`. 
The current implementation has some drawbacks:
* it has no unit tests
* it doesn't use the "id" field to match requests/responses
* it reads JSON per line, not from the stream

**Comment by duk3luk3** [comment]
> it didn't work with the Qt mainloop

Can you explain that? What exactly is the problem?

**Comment by muellni** [comment]
I was able to send requests using bjsonrpc, but never received responses or requests. Normally you'd start the bjsonrpc mainloop using [`.serve()`](https://github.com/deavid/bjsonrpc/blob/master/bjsonrpc/server.py#L106), which we can't use, because our program would hang there.
In Qt you start your mainloop with `app.exec()`.

**Comment by duk3luk3** [comment]
ugh ok, that's annoying. There are two ways to fix that, both are annoying:

a) run the server in a thread or subprocess
b) find out what the serve() code does and replicate it

I'd probably go with a) because I'm already familiar with all the annoying things I'll have to take care of then.

**Comment by muellni** [comment]
I rewrote the `connectivity.JsonRpcTcpClient` class to address the problems from OP:
- it still has no unit tests
- now it stores callbacks for request result to match the "id" field. This should fix most problems
- it still reads JSON per line, but this seems to be ok. At least I tested a `\n` in a string which got escaped properly

I'm going to close this for now and eventually reopen it if required

**Comment by duk3luk3** [comment]
Do you want me to write a quick demo for using bjsonrpc?

**Comment by muellni** [comment]
Like this demo https://github.com/FAForever/ice-adapter/blob/master/python/downlordtest.py ? Or using the Qt mainloop?

**Comment by duk3luk3** [comment]
I mean with the bjsonrpc server running in a thread
