### ISSUE TITLE
Client install fail

### ISSUE THREAD

**Issue by Nojoke185** [FAForever/client#508]
Following some testing of the ICE adapter client, attempted a reinstall of the current FAF production client (from the website) - Forged.Alliance.Forever-0.11.60-win32.msi

The client install fails midway through with the below error:

![image](https://cloud.githubusercontent.com/assets/16309355/20491142/5b62a1b4-b008-11e6-948b-5b7ff20231db.png)

log from failed install attached:

[fafinst.txt](https://github.com/FAForever/client/files/604172/fafinst.txt)

**Comment by duk3luk3** [comment]
@muellni You said this is a one-off problem caused by a specific test installer? How to fix?

**Comment by duk3luk3** [comment]
Seems this is the original error:

> ExecFirewallExceptions:  Uninstalling firewall exception2 FAF Client (C:\Program Files (x86)\Forged Alliance Forever\FAForever.exe)
ExecFirewallExceptions:  Error 0x800706d9: failed to remove authorized app

**Comment by muellni** [comment]
Use this https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed

**Comment by Nojoke185** [comment]
^^ the above link resolved my install problem
