### ISSUE TITLE
colouring of messages

### ISSUE THREAD

**Issue by tobias-strenger** [FAForever/client#510]
its probably not intended that your message is coloured red if you write your own name in chat. also this colouring is not necessary in a personal conversation.

![grafik](https://cloud.githubusercontent.com/assets/7430874/20581329/722ab644-b1d8-11e6-833d-1cf17b8e0571.png)

**Comment by duk3luk3** [comment]
:+1:

**Comment by CookieNoob** [comment]
there is actually another thing: when the conversation partner leaves the chat, the color is changed. But when he comes back online, this color stays like this. In your example would NukePukeDuke continue writing in green when he came back and pm'd you.

I think the different colors for yourself and friends/others is a good thing in pm's. This way its easier to see who wrote what.

Highlighting your own name in pm's is not necessary though

**Comment by Wesmania** [comment]
This should be fixed in rewritten chat - reopen if something still doesn't match.
