### ISSUE TITLE
Investigate map preview downloading

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#515]
New async map downloader for #506  doesn't seem to download all the maps. Maybe the previews just aren't where we're looking for them.

**Comment by Brutus5000** [comment]
Here is an example log where I just opened the client and jumped into "play" tab. (cache was cleared)
[forever.log.1.txt](https://github.com/FAForever/client/files/615064/forever.log.1.txt)

**Comment by Brutus5000** [comment]
I have debugged this yesterday. The `finishedDownload` method never gets called.
Maybe the [binding of the signal](https://github.com/FAForever/client/blob/develop/src/downloadManager/__init__.py#L21) is not correct. There are examples in the web, that do it completely different.

**Comment by duk3luk3** [comment]
Yep, no download ever actually happens. I'm debugging it.

**Comment by duk3luk3** [comment]
Please test the PR :)

**Comment by Brutus5000** [comment]
Fix confirmed.
Before:
![428-fix-before](https://cloud.githubusercontent.com/assets/6843462/20679771/9aa2a4e8-b59c-11e6-8b5f-84bb865c49e8.png)

After:
![428-fix-after](https://cloud.githubusercontent.com/assets/6843462/20679775/9c00e14c-b59c-11e6-859f-02cdee68fa22.png)

**Comment by duk3luk3** [comment]
👍
