### ISSUE TITLE
Support restoring game connection

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#522]
If a client loses connection to the server during a game, the server currently deletes the player's `gameConnection`.

With FAForever/server#237 the server will support restoring a player's game connection, but it needs to be requested by the client (because the server doesn't know whether the user's game is still running or not) using the following message:

```
{"command": "restore_game_session", "game_id": 123}
```

**Comment by muellni** [comment]
I implemented this here: https://github.com/FAForever/client/blob/feature/ice-adapter/src/client/_clientwindow.py#L1099 with commit https://github.com/FAForever/client/commit/4a29fb8a55ab15f89809a6c5bf0e51c7621a31d4 (I still rewrite commits a lot, so this link may become outdated soon)
