### ISSUE TITLE
uid-check needs the WMI service running on Windows

### ISSUE THREAD

**Issue by muellni** [FAForever/client#523]
On Windows the uid-check (by `uid.dll` or `faf-uid.exe`) needs the `Windows Management Instrumentation` service running/usable  to query system information. The client would better check the service with code like
```
try: 
    win32serviceutil.QueryServiceStatus('Winmgmt')
except:
    print "Windows service not installed"
```
to inform the user about a bad system state. Otherwise all the user's system attributes would become "invalid" and he'd be flagged as smurf.
See https://github.com/FAForever/uid/issues/7 .

**Comment by duk3luk3** [comment]
Under what circumstances would the service not be running / not be available?

**Comment by muellni** [comment]
It's not running when you turn it off and disable it. Some users may do that (Downlord wrote about 170, IDK how many are related to this).

**Comment by micheljung** [comment]
Probably happens a lot with WINE, though someone may want to test this

**Comment by muellni** [comment]
It never happened to me using wine. But I don't know about older wine versions. It's mentioned as supported in wine 1.6 release notes https://www.winehq.org/announce/1.6 .

**Comment by duk3luk3** [comment]
are we sure this isn't something that may just be missing from older windows versions?

**Comment by muellni** [comment]
I don't think this issue is important, more a nice to have. But you can reproduce it on every Windows machine and I know that there are users who like to turn off services and install registry cleaner.
