### ISSUE TITLE
Livestreams Tab 404

### ISSUE THREAD

**Issue by thygrrr** [FAForever/client#534]
**I experienced...**
 
A 404 error page.

** Repro **
In 0.12 Preview 2, click on the "livestreams" tab

**I expected...** write here what you think the best behaviour should be

Beautiful livestream goodness. (how many streamers do we still have, btw?)

**Where the bug is / What should be done** 

Remove the tab or fix livestream link.

**Comment by duk3luk3** [comment]
I believe that the problem here is that the twitch api we were using changed or was removed. Someone needs to investigate that.

**Comment by JaggedAppliance** [comment]
@HardlySoftly do you know how to fix this?

**Comment by Wesmania** [comment]
Seems above PR fixed it, we can close this.

**Comment by duk3luk3** [comment]
Indeed. We really need someone to look at finding out why the twitch api doesn't work anymore and if there's an alternative.
