### ISSUE TITLE
Player VS VS

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/client#535]
**I experienced...** hovering over a game in the games tab with 3 players showed this:
![untitled](https://cloud.githubusercontent.com/assets/21953792/21306372/e6d86aa2-c5d0-11e6-9752-d0d9476dcb89.png)

**how to reproduce** not sure

**I expected...** not a second VS and actually a list of the other players in the game.

**Where the bug is / What should be done** if you have a suggestion for fixing the issue, add it here.

**Comment by duk3luk3** [comment]
Does this happen with every game? If not do you have the replay ID for this game?

**Comment by CookieNoob** [comment]
No, this doesnt happen every game. When it shows 3/12 it should also show the other players listed there (and it usually does). I dont have the ID, I just saw that when I was online in the morning.

**Comment by duk3luk3** [comment]
OK, if you see that again, please post forever.log and an exact timestamp so we can check server logs too. It must be a problem with the synchronization of game information.

**Comment by CookieNoob** [comment]
I can post the forever.log when I come back (I didnt refaf after seeing this as far as I remember). Not sure what you need an exact timestamp for, since you can just check the replay vault to see when this game happened and there you will also see the ID. I posted this issue immediately when I saw it... so subtract a minute or 2 from the issue creation time and you have your timestamp.

EDIT: nvm I dont have the forever log I guess

**Comment by GrotheFAF** [comment]
This is handled by games\gameitem\update -> editTooltip from serverdata. This functions have currently no 'strange case' exeptions.
If you see the bug, (that state is short term (until something changes in lobby), please try to join the game and make a srceenshot.
I will look into it. ( but it's not easy to 'catch' those rare cases for investigation or even debugging)

**Comment by shalkya** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/11618427/21581903/bebb833c-d044-11e6-865c-1f1fd602c101.png)
i got this on the last public version of client

**Comment by GrotheFAF** [comment]
One reason: user in hosted game being in client offline (or only irc) {like Tokyto here -> grey host)
A user not online (in a client) had no player data (in that client).
(Other reason might be, that observer aren't handled right at the moment)
