### ISSUE TITLE
Empty Whats New Page

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/client#536]
The "What's new" tab in the client is [completely empty](http://imgur.com/a/qGMBa). Basically just a white background.

Happens to me every time i use the client. 

No idea how to fix this issue or what is causing it.

**Comment by duk3luk3** [comment]
I've been on slack with @PhilipJFryFAF. Looked at forever.log, it doesn't contain any log messages for the what's new loading process, even in debug mode. I suspect shenanigans.

**Comment by duk3luk3** [comment]
So now that we've (mostly) fixed the build, please install and run https://ci.appveyor.com/api/buildjobs/3f6firhhi3p21wmm/artifacts/dist%2FForged%20Alliance%20Forever-0.11.61-win32.msi

Same procedure as before:

* Delete everything in `C:\ProgramData\FAForever\logs`
* Add this to `FA Lobby.ini`:

```
[client]
logs\level=10
```

* Run FAF
* Log in and let it load everything (let it sit idle for a minute or two)
* Upload everything in `C:\ProgramData\FAForever\logs`

**Comment by PhilipJFryFAF** [comment]
Used the build you've linked and the "What's new" tab is now working for me again!
For some reason github can't process my file so i'll just link to a pastebin in case you wanna look at the logs.
[forever.log](http://pastebin.com/NTMj53uR)
The forever.log.1 is 1kb too big for pastebin and i'm too lazy to sort this out if you want it i can pm it to you via slack.
I guess you can close the issue now. Thank you for the help.

**Comment by duk3luk3** [comment]
the forever.log.1 would have been the important one :)
