### ISSUE TITLE
search ladder replay in vault

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#541]
1st not really important : is to make ladder1v1 the 2nd choice (2nd most likely to be search imo) in the list of mod you can choose from in replay vault. (and not the last choice)

2nd : would be great that when you search for a replay in ladder, with minimum rating, it actually look for the ladder rating, and not the global one.

**Comment by JaggedAppliance** [comment]
For your second point, that is already true, it was fixed a few months ago iirc.

**Comment by shalkya** [comment]
oh my bad
