### ISSUE TITLE
WMI check doesn't work in wine / playonlinux

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#543]
The WMI check introduced to fix #523 doesn't seem to work in Wine according to player azZ7eCh who is using PlayOnLinux in debian.

**Comment by Wesmania** [comment]
I confirm it fails to work both in latest Wine and in 1.8.3.

**Comment by duk3luk3** [comment]
I was sure @muellni once mentioned WMI is emulated by wine but I could have totally hallucinated that.

**Comment by Wesmania** [comment]
A quick search through wine bugzilla suggests that WMI implementation is partial. I haven't been ever flagged as a smurf while this fix wasn't in place, so I suppose only the check for the service fails. I can try to figure out if this can be fixed upstream.

**Comment by duk3luk3** [comment]
afaik right now we're not banning people if they deliver invalid UID data. So that could be why you'd not be marked as smurf.

At any rate, running the faf client natively in linux should work, including UID. @muellni has made aur packages for archlinux. I run the client from source in linux.

**Comment by muellni** [comment]
Do I understand it right, you're getting this dialog?
![screenshot from 2016-12-25 21-31-37](https://cloud.githubusercontent.com/assets/569476/21472834/0884f5f2-caeb-11e6-828b-1b12d312505b.png)
When you click ok, does the client run normally?

I just tested it, and apart from this wrong dialog, the client works in wine (currently using Wine Staging 2.0-rc1).

**Comment by Wesmania** [comment]
It worked fine the first time, not subsequent times. I guess since the client works well in linux and it's more of an upstream bug, it's not too important.

**Comment by muellni** [comment]
The service is indeed not running on wine.
![screenshot from 2016-12-26 13-37-31](https://cloud.githubusercontent.com/assets/569476/21482157/9a6c5f20-cb70-11e6-9bf8-5240fffcaab7.png)
I'm considering only showing a warning if the service is installed but not running. This assumes the WMI service is installed on all Windows installations.

**Comment by duk3luk3** [comment]
@Wesmania what do you mean by "it didn't work subsequent times"?

**Comment by Wesmania** [comment]
The first time I clicked OK, the game ran fine. After that I closed FAF. I thought that WMI was something I could install with winetricks, so I executed 'winetricks wmi'. What winetricks installed seemed to be some version of WMI for WIndows 9x. When I tried to run FAF through wine again, after clicking OK neither chat nor active games showed up.

The symptoms were exactly the same as when I ran the linux client without renaming the uid executable to 'faf-uid' (i.e. some failure in uid generation). I have no idea if it's winetricks that caused it to behave differently.

**Comment by duk3luk3** [comment]
Well, try to uninstall whatever winetricks installed? :-)

**Comment by muellni** [comment]
The chat and games windows not working sounds indeed like a uid authentication problem. If faf-uid can't read the uid values from WMI, the client will be disconnected. Could you please post an error log? You can find it in `$HOME/.wine/drive_c/users/Public/FAForever/logs/forever.log`
 
You can also try to run `"$HOME/.wine/drive_c/Program Files (x86)/Forged Alliance Forever/faf-uid.exe" 1234` which should print base64 bytes to stdout. But it currently crashs on my machine, maybe that's your error. I'll look into that.

And if you need to recreate your wineprefix for FAF, you can just delete the `$HOME/.wine` folder (which may delete the installed game and your game.prefs). Today I successfully created the wineprefix by using the steam version: http://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux#Install_using_steam which needed `winetricks d3dx9` and `winetricks xact`.

**Comment by Wesmania** [comment]
The game works perfectly fine when set up natively, modulo having to rename the 'uid' executable to 'faf-uid' and manually setting up wine prefix and command prefix since the relative options aren't configurable in the GUI yet. I suggest marking this one as WONTFIX and just focusing of touching up native support.

**Comment by muellni** [comment]
Yes, I'd also like a wine GUI in the client. It could write the steam-download file...

**Comment by muellni** [comment]
I think running the client in wine should be possible without annoyances. So I'll resolve this by adding an ignore-option to the message box like the admin-check does. 
Detecting wine would be an option but is bad practice...

**Comment by Wesmania** [comment]
The client is working natively now, and it's probably an upstream issue either way. We can probably close this.

**Comment by duk3luk3** [comment]
@muellni please decide if you want to keep this issue open and otherwise close it :-)
