### ISSUE TITLE
Cant update

### ISSUE THREAD

**Issue by GRfadodle** [FAForever/client#546]
If i try to update the client it updates, then closes. When i open it it tells me to update again and again. I have tried unistalling it, then reinstalling, but the same message keeps popping up

**Comment by GRfadodle** [comment]
I also use windows

**Comment by duk3luk3** [comment]
Please download this file directly: https://github.com/FAForever/client/releases/download/0.12.0-pre2/Forged.Alliance.Forever-0.12.0-win32.msi and install it.

Then please check that "C:\Program Files (x86)\Forged Alliance Forever\faf-uid.exe" was installed.

**Comment by duk3luk3** [comment]
Are you still having any issues?

**Comment by GRfadodle** [comment]
No I am not, thank you
