### ISSUE TITLE
wrong faction from ladder

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#548]
on 12.0 pre 2 (last one)

http://imgur.com/BiYzGB6

content.faforever.com/faf/vault/replay_vault/replay.php?id=5585743

**Comment by GrotheFAF** [comment]
not clear what the actual conditions were, user claims he didn't chose UEF but got UEF.

**Comment by duk3luk3** [comment]
I fixed *something*. Please take a look at this @GrotheFAF, what was the problem you said you saw?

**Comment by Wesmania** [comment]
Is this still an issue?

**Comment by shalkya** [comment]
I didn't hear any bug similar to this one occurring again recently
