### ISSUE TITLE
host abandoned lobby when host didn't

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#549]
http://imgur.com/2uhMu13

i had this pop up several time (tried to connect several time) 
hopefully got fixed after 2 refaf. happened on last version of client. 0.12.0 -pre2

**Comment by duk3luk3** [comment]
Maybe related to https://github.com/FAForever/client/issues/540

Please upload forever.log and game.log...

**Comment by Wesmania** [comment]
I'm considering this abandoned.
