### ISSUE TITLE
WebViews playing sound

### ISSUE THREAD

**Issue by Sheeo** [FAForever/client#55]
So there have been some reports of webviews playing sound, specifically the tournament webview, reported [here](http://www.faforever.com/forums/viewtopic.php?f=3&p=82057#p82057) and [here](http://www.faforever.com/forums/viewtopic.php?f=3&t=8587).

Setting

```
QWebSettings::PluginsEnabled
```

to false should disable flash ads.

HTML5 audio can be blocked through injection of JS.

**Comment by Wesmania** [comment]
Were there any more reports since then? Can we close this?
