### ISSUE TITLE
Clean up working and resources directory finding logic

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#552]
There is some code in \_\_main\_\_.py that sets up client's current directory. This directory is only used to store the RELEASE-VERSION file. If we move this file to 'res', we won't need to change directory, only to find the resources directory. Logic for this can be in turn extracted to a module.

**Comment by duk3luk3** [comment]
Sounds good to me, you can just add that to your other PR.

**Comment by Wesmania** [comment]
I think the other PR is a little bit more uncertain whether it isn't too hacky, a separate PR for this is already set up and will allow for some more on the way (editing linux res directory at install for example).
