### ISSUE TITLE
Client needs a "beta version track"

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#556]
It is currently hard to get out test / beta version of the client to users without potentially breaking their shit because the only real way to get lots of users to use a new client release is to release it as a release version, forcing everyone to update and preventing them from running old client versions.

There should be a "beta track" or "beta release" mechanism that prompts users to upgrade to beta versions (with opt-in / opt-out setting?) without stopping them from downgrading in case of bugs.

This change would have to be supported by the server.

**Comment by Wesmania** [comment]
I think we have it covered now.
