### ISSUE TITLE
Steam integration

### ISSUE THREAD

**Issue by RevoluPowered** [FAForever/client#557]
Do you have any plans to put this client on steam?

If you would like to put it up for free on steam, I have a steam-works license.

I work for a game dev company in my local area and would love to help out. I understand some licensing issues might exist, but it would be interesting to see if it could be approved.

I believe it would significantly increase the users of this platform too and increase the size of the community.

**Comment by duk3luk3** [comment]
We haven't had any plans to do that so far. Could be a good venue.

What licensing issue would there be? The client itself is GPL3-licensed (and hopefully clean, I haven't personally checked if all the libraries we use are GPL-compatible...). The game is a bit hairier of course but at the end it's just a mod for Forged Alliance.

**Comment by RevoluPowered** [comment]
Yeah, I thought it might break the EULA distributing a modification on steam but now I think about it, provided it's not modifying the executable, it should be fine.

Not saying I've read the EULA of course, someone would probably need to check. 

Steam integration would be good too because the SteamAPI makes it easier to join friends playing, steamworks integration is relatively easy to achieve too.

Plus free advertising for FAF, and less resources are required to distribute the game client because it would then be distributed by the steam servers.

**Comment by duk3luk3** [comment]
> Yeah, I thought it might break the EULA distributing a modification on steam but now I think about it, provided it's not modifying the executable, it should be fine.

We ship our own executable :P

> someone would probably need to check.

Yes, whoever does the implementation work should also do that :-)

**Comment by RevoluPowered** [comment]
Just checked the EULA, since distributing the executable is not permitted this might be an issue.

I'll see if I can contact the current owner of FA, and get their permission to do this. Since THQ is toast and the EULA distributed with steam doesn't reference any other company, it might void the EULA. This is speculation though, will update this once I find out more.

"You may not transfer, distribute, rent, sub-license, or lease the Software or documentation, except as provided herein; or alter, modify, or adapt the Product or documentation, or any portions thereof."

**Comment by RevoluPowered** [comment]
EULA http://store.steampowered.com/eula/eula_9420, which is potentially void due to a non existent company reference.

**Comment by duk3luk3** [comment]
Many people have tried for a long time to get anything out of "the current owner of FA", whoever that was at any point in time. I don't think there's been any success.

**Comment by RevoluPowered** [comment]
Ah okay, I've just emailed their legal contact so, we will hopefully get a response at some point.

**Comment by RevoluPowered** [comment]
Finally found out who properly owns the game, and who to actually contact.

 "Gas Powered Games was acquired by Wargaming.net" - These people.

**Comment by duk3luk3** [comment]
I'd recommend you talk to @Sheeo and/or visionik to find out what has been done and what agreements may already have been made in regards to the copyright / trademark of SupCom / FA before you go chasing after people :-)

**Comment by Wesmania** [comment]
Steam would be tough. Considering this abandoned.

**Comment by RevoluPowered** [comment]
Yeah, I got in touch with war gaming to discuss it but they never got back to me.
