### ISSUE TITLE
like and comment mods (mod vault)

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#559]
http://forums.faforever.com/viewtopic.php?f=40&t=13708

comment doesn't work
like doesn't work and make you disconnect.

why ? 
server doesn't support old method of interacting with mod vault anymore
it tells the client that it's an invalid operation
and invalid operations cause the client to disconnect

we need to either make server and mod vault interact again; or we remove like and comment from the feature.

**Comment by duk3luk3** [comment]
Since I haven't seen anybody raise their hand to integrate the api, I'll disable it.

Transitioning to use the API fully is still a high-priority task.
