### ISSUE TITLE
Refactor Client

### ISSUE THREAD

**Issue by thygrrr** [FAForever/client#56]
I would like a more testable Model-Presenter or Model-Controller relationship between the actual core modules and the individual tabs (presenters in this context being views+controllers in one thing) in order to make code more testable and modular. (a nice start was done in the new-protocol branch, I think it needs to go much further than that)

I would also like to refactor basically every "communications" component into a Logic and View part.

Without overdoing this, this should get us a nicer architecture in proper increments. It will also allow us to swap out the client code to a different protocol version as well.

Long-Term-Goal would be an actual MVP architecture, but this is out of scope for this issue.

**Comment by Wesmania** [comment]
I'll close this for now, it's too vague IMO.
