### ISSUE TITLE
Chinese localization request

### ISSUE THREAD

**Issue by K-Hideyoshi** [FAForever/client#561]
I'd like to provide Chinese localized strings_db.lua file from steam version game.
Could you please add it to FAF?
[strings_db.lua](https://drive.google.com/open?id=0B1Vpfxhj3KeFSm9WYUJSNXlEZE0)

**Comment by Wesmania** [comment]
This should be reported to the FAForever/fa repository. Reopened [here](https://github.com/FAForever/fa/issues/2346).
