### ISSUE TITLE
Fix requirements.txt

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#566]
Currently getting a dev environment set up in Windows is a huge pain. The client's `requirements.txt` is a mess.

TODO:

- [ ] Make a `requirements-dev.txt` that only includes stuff needed for getting `python src` and `python runtests.py` to work
- [ ] Get proper releases of `faftools` going so we don't need its dependency as a git url
- [ ] Figure out if we need all the requirements
- [ ] Annotate requirements with comments as to what they're needed for

**Comment by Wesmania** [comment]
I made some general cleanup of deps. Faftools isn't needed anymore, and I feel the remaining deps are self-explanatory or easily greppable. I'll close this.
