### ISSUE TITLE
replay vault saved searched

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#569]
would be nice if replay vault keep the last search loaded. 
for exemple you search in replay vault, launch a replay, then switch to aeolus chat, and then come back to replay vault when replay is over and don't need to search again (since the search would be saved up)

so is it possible to not only have setting for searching saved, but the actual search is saved (not sure if you understand), so we don't need to search again. 
Would be a nice little improvement imo. But don't bother if too hard to achieve.

**Comment by duk3luk3** [comment]
I think what we're doing for #414 should fix your problem.

**Comment by duk3luk3** [comment]
Please install https://ci.appveyor.com/api/buildjobs/melq6sp3a2d57v6g/artifacts/dist%2FForged%20Alliance%20Forever-0.12.0-win32.msi and see if that makes the replay vault work the way you want!

**Comment by shalkya** [comment]
that's perfect <3
