### ISSUE TITLE
Unsure as to what version of where to obtain PyQt4 4.7+

### ISSUE THREAD

**Issue by RevoluPowered** [FAForever/client#574]
Does anyone have a link to PyQT4? (Googled about; it's the only thing I'm missing at the moment)

Currently running on the windows 10 platform.

**Comment by duk3luk3** [comment]
The recommended way to install it is using Miniconda. See instructions for setting up dev environment on Windows here: https://github.com/FAForever/client/wiki/Windows-Dev-Environment-with-Miniconda

**Comment by RevoluPowered** [comment]
Thank you for your help, I will give this a try now.

**Comment by duk3luk3** [comment]
Do you need any more help with this or can we close this issue?

**Comment by RevoluPowered** [comment]
You can close it :)
