### ISSUE TITLE
Remove "create_account" message

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#577]
Account creation should no longer be done by sending the now deprecated `create_account` to the server. Instead, either the API should be called or the website opened.

**Comment by duk3luk3** [comment]
We wanted to restrict sign-ups to website only in the long term to have more control against fraud and smurfs, didn't we?

**Comment by micheljung** [comment]
Restricting account creation to the website doesn't help against "fraud" (what kind of fraud?) or manually created smurf accounts. It would, however, along with a captcha help against automated account creation.

Without a captcha we can as well just open the API.

**Comment by duk3luk3** [comment]
I think the registration should just be changed to a link to the website then. What's the correct link?

I suppose it's https://www.faforever.com/account/register...
