### ISSUE TITLE
Check for updates autonomously

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#578]
The client should not be informed by the server about new client versions. Instead, it should check autonomously, e.g. against GitHub or the FAF-API.

**Comment by duk3luk3** [comment]
Will there still be a version check on the server at all? There should be a check whether client and server are compatible, or some kind of versioning of the server interface.

**Comment by micheljung** [comment]
Yes, the server can still check whether the client is compatible or not. I recommend a `PROTOCOL_VERSION = 1` for this purpose, so the server can deny incompatible clients.
