### ISSUE TITLE
Outdated theme version popup on client start every time

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/client#583]
**I experienced...** a pop up that pops up explaining to me that my theme is outdated and i should contact the author - when in reality the theme works perfectly fine but only the version number in it which is hard-coded does not match

this means for every single client release and pre-release i would need to update that version file for every theme, and then EVERYONE using them needs to get the new version and go through a painful installation process that feels more like a hack to update. This is the main reason no one uses themes. my first themes had 300 downloads and now i resort to private clan use and only a few individuals
picture: http://puu.sh/tm3ml/ca9dc3f0c5.png

**how to reproduce** create an empty theme with just the version number in it and make that version number say anything except the current build version
to ease your suffering i have made one for you:
http://puu.sh/tm3Fx/a986552b02.rar
install it like you would any other theme:
extract file into C:\ProgramData\FAForever\themes
restart faf
select the theme from the faf menu: Options>theme>(themename) 
faf will restart and should give the popup - you can also check if the theme is working by looking in the menu.

**I expected...** a checkbox should appear saying dont show again until next update and it will go away after that

**Where the bug is / What should be done**  as above, an alternative would be to use black magic to only make the popup appear on a major version change but that requires more work, and i think the checkbox does a better job anyway.

**Comment by duk3luk3** [comment]
> use black magic to only make the popup appear on a major version change

This is not black magic: http://semver.org/

I'm planning to keep to the semver spec in the future and make a major release every time we make backwards-incompatible changes.

I'll figure out how the version check works and fix that, and add a dismissal button to the popup too.
