### ISSUE TITLE
Watching old replays requires deleting gamedata files

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#590]
**I experienced...** "An error has occurred in the faf client" appears when trying to watch replays from previous patches. It downloads the files then gives the error message, then it remains 'updating' indefinitely

**how to reproduce** try to watch replays played under different patches.

To get past this you have to delete your gamedata files and allow them to be downloaded again. 
Apologies if this is in the wrong repo.

**Comment by duk3luk3** [comment]
This is probably a problem with the game updater. It doesn't really work properly for "downgrading".

There's been work on alternatives which I hope will come to fruition some time soon.
