### ISSUE TITLE
[ICE] Alpha testing

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/client#592]
*Only for Testing*
To test the nodejs ice implementatin

[dist.zip](https://github.com/FAForever/client/files/730651/dist.zip)

1. Extract the files from `dist.zip` somewhere
2. Install nodejs: https://nodejs.org/en/
3. Run `npm install --production` in the folder with the `package.json`
4. Start the Adapter from the client with `node faf-ice-adapter.js ...`
For Parameters see: https://github.com/FAForever/ice-adapter#commandline-invocation
e.g. `node faf-ice-adapter.js --id 123 --login Rhiza`

# Result
* Player should connect over ICE-Adapter
* Player can start a game
* Player can play a game

**Comment by muellni** [comment]
There's a ready-made setup now: https://github.com/FAForever/ice-adapter/releases/download/v5.0.1/Forged.Alliance.Forever-0.12.0-win32.msi

**Comment by muellni** [comment]
Latest build is here: https://ci.appveyor.com/api/buildjobs/o73x8y9m286y2rcc/artifacts/dist%2FForged%20Alliance%20Forever-0.12.0-win32.msi
