### ISSUE TITLE
Use Auth for Appveyor requests to Github

### ISSUE THREAD

**Issue by muellni** [FAForever/client#597]
We need to use some [authentication](https://developer.github.com/v3/#authentication) to circumvent being hit by [rate-limiting](https://developer.github.com/v3/#rate-limiting) in the Appveyor (and Travis) builds. Example of a build being hit by rate-limiting: https://ci.appveyor.com/project/Sheeo/client/build/1301

**Comment by duk3luk3** [comment]
#538 just needs to be merged, I'll do that asap

**Comment by duk3luk3** [comment]
Done.
