### ISSUE TITLE
Replay search in vault by map not working

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/client#599]
Searching the replay vault by map name does not produce consistent results.

E.g. search for 'Tag Craftious Maximus' or 'Esgaroths Ruins' never produces any results
Search for 'Seton's Clutch' produces only results for 'Fun Setons'

Search should be better! Searching for 'Tag' should produce any results with 'Tag' characters in them. Should be case insensitive.

**Comment by duk3luk3** [comment]
The search seems pretty terrible, I agree.

**Comment by GrotheFAF** [comment]
Nothing can't be done about that from client (alone).
The search parameter are handled by secondary server:
https://github.com/FAForever/legacy-secondaryServer/blob/master/replays/replayServerThread.py#L584

**Comment by Wesmania** [comment]
Is this still a client problem?

**Comment by GrotheFAF** [comment]
It kinda still is. We learned meanwhile, with the proper use of wildcard (for blanks and '), one can do a search for the intended map. Question is, who knows that.
One could think of some kind of autocompletion map list, to assist with that. (which has it's own problems considerig the amount of maps, so maybe only for the usual suspects)

**Comment by GrotheFAF** [comment]
It kinda still is. We learned meanwhile, with the proper use of wildcard (for blanks and '), one can do a search for the intended map. Question is, who knows that.
One could think of some kind of autocompletion map list, to assist with that. (which has it's own problems considerig the amount of maps, so maybe only for the usual suspects)

**Comment by GrotheFAF** [comment]
oh... stupid me .. that wildcard replacement could be implemented.
