### ISSUE TITLE
Coop missions does not work

### ISSUE THREAD

**Issue by Sergey-Terekhin** [FAForever/client#601]
**I experienced...**

When I try to start coop mission, bug report window is appeared
FAF client version is 0.12.0-pre3 + 1276

In some older versions coop missions worked correctly

**I expected...** 

Mission is started

**Comment by duk3luk3** [comment]
Please use "delete gamedata" function in client or remove C:\ProgramData\FAForever directory.

**Comment by Sergey-Terekhin** [comment]
It works, thanks

**Comment by duk3luk3** [comment]
Please post to Tech Support forum first next time.
