### ISSUE TITLE
Install Support Plans

### ISSUE THREAD

**Issue by thygrrr** [FAForever/client#61]
@Sheeo and I just had a lengthy chat on which versions to support, legalities of how the FAF patch currently looks, and what we want to do.
## Supported Versions
- Forged Alliance 1.5.3599 (official Retail)
- Forged Alliance 1.5.3603 (beta Retail)
- Forged Alliance Steam
- Supreme Commander 1.1.3280 (official Retail)
- Supreme Commander Steam

We may want to discontinue support depending on the patch requirements.

We will explore the possiblity of creating and providing a community patch from Retail, Retail 3599, and Retail 3603 to Steam, as well as a Supreme Commander patch from Retail and Retail 3280 to Steam - which would make the FAF "mod" much slimmer.
## Mode of Operation
- FAF clones the bin directory and compares it to one of these versions
- It applies binary patches to bring relevant files up to the right version
## Licensing Issues

The patches are derived works, which are most likely not GPL3-compatible.
## Unauthorized Copies

Unauthorized Copies are not supported and not encouraged. GPL3 warrants there will be no DRM in the Lobby or associated components. :+1:

**Comment by arkitect-dev** [comment]
Is this still the correct info for support fa? I'll get a wiki master to add this if its current

**Comment by Wesmania** [comment]
What is the situation on this right now?

**Comment by Wesmania** [comment]
I'll close it, assuming inactive.
