### ISSUE TITLE
Github updater displays the update prompt twice

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#612]
The new github updater shows the update prompt twice when you force the reported version to an outdated one. This is caused by calling the updater in 2 places - handle_update and github_update. The latter is called depending on what version we find in git, the earlier depending if the server tells us that our version is outdated. We should probably unify these checks somehow.

**Comment by duk3luk3** [comment]
Yes.

When fixing this, you need to take into account that updates from server are mandatory, updates from Github aren't. (General you - not saying you specifically should fix this.)

**Comment by Wesmania** [comment]
One additional problem is that the server only notifies us about the update when FAF is outdated. It would be nice to fix it server-side so we simply always receive the version number of the oldest supported version.

In particular, the code that interests us on the server is in server/lobbyconnection.py:820 and server/lobbyconnection.py:656.

**Comment by duk3luk3** [comment]
This will be solved by removing the update via the server entirely and replacing it by versioning the client<->lobbyserver protocol.
