### ISSUE TITLE
Error when updating FAF client

### ISSUE THREAD

**Issue by sebastianpiskorski** [FAForever/client#617]
**I experienced...**

When I did run faf-client, it have notified me about outdated client I got such CLI error during update: 
```
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:process:SetProcessDEPPolicy (1): stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
```

**how to reproduce** 

I gues you just have to run client and try to upgrade it.

**I expected...** 

To upgrade FAF client without any errors.

**Where the bug is / What should be done**

I don't know python. Looks like wine error.

**Comment by duk3luk3** [comment]
Wine is not an officially supported platform and we're not going to add workarounds for deficiencies in wine. If the updater doesn't work in wine, well that's that. Update manually.
