### ISSUE TITLE
Rework the "Whats New" Tab

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/client#62]
Maybe renname the tab to "Community".

Content of the tab cleaned up:

-News (including next tournements, force TD's to write one, or make it automatic if possible)
-Latest Casts
-current active Livestreams 
-Donate

If needed make sub-tabs or something similar with: 
-mumble
-stats that are currently displayed, or more
-other links, if they are not placed at the top bar: Clans, Username change, Password recovery, Forum, Wiki, Unit DB, anything community related

-When there is an active livestream, change the icon of the tab to something animated and colorfull (maybe a running TV) to make it easy visible that someone went live without having to check the tab
-When there is an unread news, change the icon of the tab or make it colored or something too, to assist people in reading news. Don't know if you are able to check if someone has already visited the news page already since the last news though. 

-Remove livestream tab in return 

-Don't try to run livestreams in FAF. Let them open in your browser instead. 

Very bad mockup, please remember i have nothing to do with design :) 

http://i.imgur.com/Guy4Yiu.png

**Comment by Wesmania** [comment]
Got reworked once already, serves us well for now. I'll close this for now.
