### ISSUE TITLE
Games list stops updating after some time

### ISSUE THREAD

**Issue by Viba** [FAForever/client#623]
After X amount of time the custom games list stops updating itself, list keeps showing the old games that existed up to the point where the updating stops functioning. Restarting client solves it.

**Comment by duk3luk3** [comment]
Would be great to have logs for this.

**Comment by Viba** [comment]
Will add logs when and if I get them.

**Comment by GrotheFAF** [comment]
welcome to the club ;-)
I reported this often happening to me (it still does) in forum, but no one cared. (because it was just me...) and nothing to see in (my) logs.

**Comment by Wesmania** [comment]
Is this still happening?

**Comment by Viba** [comment]
Yes, with longer uptimes the game list stops updating properly. Just this last week I seem to recall it updates some of the games but doesn't include all of them, refaf solves it.

Like a friend can ask to join a game -> I open the play tab and see games changing and people joining, but it doesn't have the newly hosted game.

**Comment by GrotheFAF** [comment]
Yes it is still happening here. The server stops sending updates port 8001.  (nothing in log)
(My client version in XP has a monitor for that, the W7/develop version doesn't, so not sure how often it happens under the develop version)
I noticed some correlation: It happens earlier the more (other PCs) ul traffic is going over my router.

**Comment by Wesmania** [comment]
We'll have to investigate if it's the server that stops sending the info or if the client fails to receive it, then.

**Comment by GrotheFAF** [comment]
TCPview shows no more traffic on the port 8001 connection.

**Comment by Wesmania** [comment]
Hmm, then I guess we could escalate it as a server issue. Also, could this mean simply losing connection to the FAF server without the client noticing? Connecting some debug code to signals of whatever socket is used to communicate could help us figure that out.

**Comment by GrotheFAF** [comment]
The problem is since the Feb 2016 update, and I talked to server guys about it, but not much interest there to investigate (I guess because it was [just] me.)
