### ISSUE TITLE
Over time users who are offline are accumulating and shown as online

### ISSUE THREAD

**Issue by Viba** [FAForever/client#624]
If I leave my client open for a longer period of time the shown amount of online users starts to climb compared to a regular IRC client. Offline users are still shown as online in the client.

The longer the client is opened the more it will show offline users as online.

**Comment by Wesmania** [comment]
We had handling user renames implemented lately, it might be worth testing to see if we still report too many players.

**Comment by Viba** [comment]
Indeed, the client seems to keep track of logged in users in #aeolus correctly now.
