### ISSUE TITLE
Usernames get "_" added in the end

### ISSUE THREAD

**Issue by Viba** [FAForever/client#625]
I assume if people refaf/reconnect before their previous "session" is properly terminated, they get a tail added after their nickname. The thing is that regular IRC clients cope with this and show the normal "username" while the FAF client might show the "username_" variant, seems to be local as well, others might just see username. Occasionally you see duplicates of "username" and "username_" aswell.

**Comment by Viba** [comment]
I guess this is the difference: http://puu.sh/ua5GT/3245044554.png

irc on top, faf client on bottom

**Comment by yorick-ne** [comment]
i'm not sure on this, but it is probably because the `on_nick` event isnt handled in the client (except for logging it). 
if this is the case there should be something like "[nick:username->smth_else]" in the servertab. 

Edit: I just had the client running for a bit and this was in the server tab:

> [nick: max8391_!202699@B9E2D973.5A30FB4A.55962AD3.IP->max8391]

**Comment by duk3luk3** [comment]
> `on_nick` event isnt handled in the client

Whelp. That needs to be fixed, definitely.
