### ISSUE TITLE
Auto-join language irc channels

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/client#63]
Self explaining I hope. :) 

The issue with that is that it will create many unmoderated channels. A possible solution I thought of:

Any moderator for the channels will join automaticly. If there is at least one moderator in the channel, everyone else will also join automaticly, otherwise not. The most popular languages will hopefully have a moderator online most times. 

Or will that lead to too much confusion?

**Comment by Wesmania** [comment]
Does anyone want this in still?

**Comment by Wesmania** [comment]
(Finally) done.
