### ISSUE TITLE
Typo in gamesession.py breaking rehost feature

### ISSUE THREAD

**Issue by yorick-ne** [FAForever/client#630]
**I experienced...** Ingame Rehost feature not working.

**how to reproduce** Host and start a game, press rehost in the ingame menu. Error popup in the faf client appears. No game gets hosted.

**I expected...** a new game being hosted with same settings.

**Where the bug is / What should be done** There appears to be a typo in gamesession.py. 
https://github.com/FAForever/client/blob/develop/src/fa/game_session.py#L176
Everywhere else in this file the client is being referred to as` self._client`.

**Comment by duk3luk3** [comment]
Good catch.
