### ISSUE TITLE
Strange symbol in forever.log

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/client#648]
When trying to copy paste the whole log I've noticed  that just part of it got pasted even thought I hit Ctrl A to select all. So when I went to the last line I found this there:
https://puu.sh/uuXaw/9206e69be6.png

Not sure how severe that is if all. The replay was a FAF Beta mod where I did some testing for Icecreamer.
When searching replay vault it is there but missing end time
https://puu.sh/uuXgk/d26a4f9c1b.png

**Comment by Wesmania** [comment]
It seems the null byte is part of protocol, and it's needlessly logged. #649 should fix the logging.
