### ISSUE TITLE
"Remember me" in login wizard doesn't work

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#651]
The "remember me" checkbox in the login wizard is supposed to set the same property that the client's "automatic login" checkbox does, but for some reason changing it has no effect.

**Comment by Wesmania** [comment]
The code is somewhat of a quagmire. A quick fix is possible, but not high-priority I think. It should be much easier to fix once #563 is in place.

**Comment by duk3luk3** [comment]
I think you're wrong about that. The "remember me" checkbox controls whether username and password are remembered. the "automatic login" checkbox controls automatic login.

Perfectly logical.

**Comment by Wesmania** [comment]
Check [src/client/loginwizards.py:{83,120}](https://github.com/FAForever/client/blob/develop/src/client/loginwizards.py#L83) and [src/client/_clientwindow.py{709,728}](https://github.com/FAForever/client/blob/develop/src/client/_clientwindow.py#L709). They set the exact same config option.
If these two things are supposed to be different, then either we should reword them to be the same or figure out a reasonable logic for two different options.

**Comment by duk3luk3** [comment]
Huh, you're right. I blame muellni for once telling me something different, maybe I misunderstood.

Of course my "Perfectly logical" was sarcasm, the current state is terrible.

**Comment by Wesmania** [comment]
Seems to be working now.
