### ISSUE TITLE
Ladder tab

### ISSUE THREAD

**Issue by Zockyzock** [FAForever/client#66]
-Either rework the ladder system or remove it for now, and use only the trueskill "ladder". This has nothing to do with the lobby directly though. 

-If it will be kept, it will probably need a redesign. Suggestion: copy LoL a bit :D 

http://rowango.files.wordpress.com/2013/11/gold-v.jpg

-Your division and name of it will be displayed all time in the ladder tab, and you get a congratulation popup when you advance. 
-Otherwise display the whole ladder with all players in it, like the trueskill ladder works now. Make it possible to see a list with players of your division, but not every other single division is needed.
-move the map stats to the place where the other stats (currently only user numbers and top5 players) are
-add clan rankings (using average trueskill of all clanmemebers), and maybe a clan ladder in some future (though no idea how that could work)
-If the trueskill ladder is selected, it should show your "player statistics" instead of the league info, next to rank and win rate etc. So you could remove that extra-window that is currently showing the statistics. 

super artistic mockup:

http://i.imgur.com/corh07Z.png

another with less free space:

http://i.imgur.com/p9V2RjC.png
http://i.imgur.com/55mH5KL.png

**Comment by arkitect-dev** [comment]
closing as divisions are no longer used
