### ISSUE TITLE
IRC messages from foes

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/client#660]
Messages from foes in aeolus are visible and highlighted in red.

no clue how to reproduce

they should be invisible

no idea what is causing this

[client log](http://pastebin.com/ABnipR5W)

**Comment by Wesmania** [comment]
Is this still an issue in 0.15.1?

**Comment by ghost** [comment]
So I have tried to foe but I don't receive any message after the user was an foe, but if it happens in rare/special occasion it doesn't prove that it is fixed.
I'm wondering if it has been fixed by the updates or if it is still happening. Posted on the forum, waiting for answers on the forum.

**Comment by ghost** [comment]
Ah, finally got an answer for it, someone had foed someone else and could still read the message from the foed person. He was not totally connected (irc user). So the bug is still there.

**Comment by PhilipJFryFAF** [comment]
fixed with #854
