### ISSUE TITLE
Port the client to PyQt5

### ISSUE THREAD

**Issue by muellni** [FAForever/client#662]
Arch Linux dropped QtWebkit from the `python2-pyqt4` package. Probably because it's an ancient security nightmare. This forces me to hold back package upgrades. `python2-pyqt5`contains QtWebkit though. Porting should be simple, but touches a lot of code.

After ICE™️

**Comment by Horcrux** [comment]
I ran into this issue today. Worked around it by installing a pre-2015 version of PyQt4 from the old ubuntu repos. Would be great if future generations could be spared the headache.

**Comment by muellni** [comment]
#509

**Comment by muellni** [comment]
client should now run on Linux with Python3 and PyQt5: https://github.com/FAForever/client/tree/474-feature-py3
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-fafclient
