### ISSUE TITLE
Mapvault is not themed

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#667]
Mapvault is set up to load a "res/vault/style.css" stylesheet if it exists. It doesn't, though, which makes the map vault look horribly ugly.

**Comment by PhilipJFryFAF** [comment]
you mean like [this](https://puu.sh/uNqUt/b44f6053a4.png)?

**Comment by Wesmania** [comment]
Precisely.

**Comment by ghost** [comment]
The image link is dead :(
Is the issue still there ? I don't see anything really ugly on the map vault but maybe I'm too lenient or something.

**Comment by Wesmania** [comment]
I discovered later that the map vault is actually a php file run on the server and what we're seeing in the client is a web browser view for it. In other words, it'll have to be rewritten completely using the java api, so I'll close this.
