### ISSUE TITLE
Kill off mumble code

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#681]
Mumble integration has been gone since forever, but there are still leftover bits of code in the client. Let's purge them.

**Comment by duk3luk3** [comment]
We used to have fully working mumble integration. what happened?

**Comment by Wesmania** [comment]
There is 3bd41ab25a9a280891ef7b9c64aaae4b19809043, apparently it was broken for a long time and was removed. I have no idea what kind of "serverside implementation" the commit is talking about, either.
