### ISSUE TITLE
Replay vault: filter out test games

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#706]
It would be nice to be able to filter out games with only one person, test games fill the vault with spam and make it hard to search.

**Comment by GrotheFAF** [comment]
Currently, the number of player (or any player info) isn't part of the server response message to a search  in Replays.
(To get the player info, you would have to ask info_replay from server for each replay from search, which seems a bit much.)

**Comment by duk3luk3** [comment]
This should be fixed in the Java-API where we'll eventually be pulling replay info from, and @micheljung already said it's easy to do.
