### ISSUE TITLE
Automatically use 'foo' as password on test lobby server

### ISSUE THREAD

**Issue by muellni** [FAForever/client#712]
One of the last annoying points in my ICE test beta client is that the user has to reenter the password when he switches back from beta to production client.
I suggest to make the client detect that the test lobby server is used and override the supplied password with `foo`. 
This way we don't touch the stored password for production.

**Comment by Wesmania** [comment]
I'd love to work on this on top of #653. Changing login widget stuff around in what we have currently is a pain, and it'd take just a handful of lines to implement that on top of that PR (including not having the widget snoop around the client object).

**Comment by muellni** [comment]
Thank you, this would be a nice to have for public ICE test. I'll rebase my ICE branch, just ping me when ready :)

**Comment by muellni** [comment]
You're using [`config.is_beta()`](https://github.com/FAForever/client/commit/dfcaa16790069517a04fd67f15c0dc66fd15f6d6?diff=unified#diff-fec04f0d6c9f34888f0f19fa260ce0f6R1065) but I suggest to detect using the test server instead. `config.is_beta()` could also be true for production server clients I guess.

**Comment by Wesmania** [comment]
Am I supposed to do that by looking at the host string? `is_beta()` is indeed a misleading name, but it simply checks if the environment is development, and I think it's the authoritative thing in deciding if we're connecting to the test server.

**Comment by muellni** [comment]
Sorry, you're right, `defaults['host'] = 'test.faforever.com'` is not from my ICE branch.
