### ISSUE TITLE
Replay search fails for some after the recent server update

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#731]
Some replay searches (eg for some users) don't show any Replays.

After the recent server update some replays (7773 - downlord info) have negative duration.
The client is currently not prepared to handle negative durations.
if the negativ is below one day - the client shows  24h + (negativ) duration.
(for example: duration -1h10m is shown as 22h50m - specially duration -1 becomes 23:59:59)
if the negative is over one day the client prduces a (silent) error and no replays are shown.

2 Options here:
1. fix the replays - by making sure all data is corrected so duration is positiv.
2. let the client handle negavite durations.

**Comment by duk3luk3** [comment]
Fixes that need to be made:

* Definitely stop using `gmtime` for duration
* Definitely not choke on invalid data

**Comment by GrotheFAF** [comment]
What would you 'definitly' use for duration instead of gmtime?
(gmtime was used for duration since I started and you were 'definitely' ok with it, until now)
