### ISSUE TITLE
EcoManager "missing dependency" lobby UI bug.

### ISSUE THREAD

**Issue by Arkemlar** [FAForever/client#739]
**I experienced...** The "missing dependency" message shown under EcoManager mod in UI mods menu. 

**how to reproduce** This only occurs when you join some game and open UI mods menu. If you hosting game - you can normally pick this mod on.

**I expected...** Expected to normally select the mod since missing dependency is bug because I have this dependency (common mod tools) and EcoManager works normally.

**Where the bug is / What should be done** fix bugged "missing dependency" message.

This is required because if you want to change UI mods set, you have to host your game, change mods settings, and then join desired game.. otherwise you will save changes with eco manager being in disabled state.

**Comment by Wesmania** [comment]
This is an issue with the ingame lobby code, so it falls under [here](https://github.com/FAForever/fa). You can reopen it there.
