### ISSUE TITLE
Unit database tab has the Twitch icon

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#740]
As the title says. I'm not sure what a good replacement icon would be, maybe an acu icon?

It has the twitch icon because it used to be the livestreams tab in case anyone is wondering.

**Comment by duk3luk3** [comment]
That's because someone needs to make the livestreams tab work again.

**Comment by Wesmania** [comment]
We can still make an issue to add a units DB icon though, I'm sure we'll be doing a livestream tab from scratch anyway.

**Comment by GrotheFAF** [comment]
That Unit-DB icon was newly designed by Schmidt&Hirsch-Design Hamburg (and these guys aren't cheap). It symbolizes units on an info-sheet, it only coincidently looks alike the old twitch icon. ;-)
