### ISSUE TITLE
Cleanup convoluted resize logic

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#747]
Client uses some resize logic that's used by channel widgets, in an attempt to make resizing more efficient it seems. It doesn't work anyway and resizing still eats a lot of CPU. We should clean this code up for now, and worry about such optimizations some other day.

**Comment by duk3luk3** [comment]
(Added to Next for now, if you can make a quick PR I'll put it into 0.12.X)

**Comment by Wesmania** [comment]
#748
