### ISSUE TITLE
notice from server prompt spacing

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/client#752]
https://files.slack.com/files-pri/T02T320UA-F5U6Z92HK/pasted_image_at_2017_06_15_10_30_am.png

would be great if we could fix the spacing and remove those tags

**Comment by ghost** [comment]
The message is sent by the server in player_service.py file (it should be moved to server issue, not client issue) : 
```
                    player.lobby_connection.send_warning("""
                    The server has been shut down for maintenance, but should be back online soon. If you experience any
                    problems, please restart your client.<br><br>We apologize for this interruption.""")
```
There is a bad spacing + br tag should be removed too.

**Comment by ghost** [comment]
I added the issue on server side : https://github.com/FAForever/server/issues/323
So this issue should be removed/closed.
