### ISSUE TITLE
Client Updater strips prerelease information

### ISSUE THREAD

**Issue by duk3luk3** [FAForever/client#753]
Due to old versioning troubles, the client updater performs [this](https://github.com/FAForever/client/blob/develop/src/client/updater.py#L39-L42) to isolate the client installer version:

```python
                curr_ver = config.VERSION.split('-')[0]
                if Version(tag) > Version(curr_ver):
                    self._logger.info('Should update {} -> {}'.format(curr_ver, tag))
                    self.update_found.emit(js)
```

Since we are now going to have "0.X.Y-rc.Z[-commits]+BUILD" version numbers, this needs to be changed.

**Comment by duk3luk3** [comment]
TODO:

* [ ] Look at build process / versioning code to figure out the definitive form of version strings and if need fix it up a little
* [ ] Fix up the `config.VERSION.split('-')[0]` code from above
* [ ] Test it (Make releases to your own repository fork and adjust the url the updater checks)

**Comment by Wesmania** [comment]
I did some work on consistent versioning over here:
https://github.com/Wesmania/client/tree/new-versioning
I think it could serve as a definitive versioning scheme, I'll just need to rebase the branch a little to make it merge-ready.

**Comment by Wesmania** [comment]
If we want to introduce the above, it'd be best to first pull in #750, rebase #572 on top of it, pull in #572, then pull in the above branch.

**Comment by Wesmania** [comment]
I added a commit that doesn't strip the prerelease version and made mock releases 0.14.0-pre1, 0.14.0-pre2, 0.14.0 and 0.14.1-pre1 (in order from oldest to newest). I tested upgrade prompts for each combination by checking out each tag and modifying github url to return specific tags. The update_found signal is indeed sent if and only if current version is older than the new one.

**Comment by Wesmania** [comment]
Prereleases should be hidden from the updater if we use a '*/latest' url. I also assume that the version sent from the server is set to something that won't cause any trouble, so we should be good to go. If we want to pull the patches onto the staging/0.13.x branch instead of develop, I suppose we can first pull them into develop, then cherrypick the new commits to staging/0.13.x.
