### ISSUE TITLE
From chat user 'View Replays in Vault' doesn't show replays if rating <0

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#762]
I searched User Yucassha and it only showed one replay. (and not the one I just played against him)
After I set 'Min rating' to -100 the other replays (ladder rating below zero) showed up.

I would expect that chat user 'View Replays in Vault' shows all replays of a user.

One solution would be to set minRating  in chatter.py/viewVaultReplay to a reasonable negative value.

A better solution would be a flag that makes the server ignores the minRating in the query. (which could actually be if minRating == 0)

**Comment by Wesmania** [comment]
Somebody could legitimately want to set minRating to 0. We could just send a really low negative value if the restriction is "disabled".

**Comment by ghost** [comment]
This issue should be closed by the way (cf PR)

**Comment by Wesmania** [comment]
We'll close it once it's merged. You can add a 'Fixes #762' line to the commit description to autoclose it at merge.

**Comment by ghost** [comment]
Ugh, I may be wrong but pretty sure the PR has already been merged : https://github.com/FAForever/client/pull/878 so...?

I see for the autoclose, I didn't know that. I did 'Fix issue #762' in the commit message instead of 'Fixes #762'.

**Comment by Wesmania** [comment]
Alright.
