### ISSUE TITLE
GameSession class doesn't check if we're still connected to the game before sending things to it

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#764]
We've got reports of exceptions along these lines:

```Traceback (most recent call last):
  File "src\client\connection.py", line 237, in readFromServer
  File "src\client\connection.py", line 315, in dispatch
  File "src\fa\game_session.py", line 116, in handle_message
AttributeError: 'NoneType' object has no attribute 'send'
```

These are caused by the code that talks to the game not checking if the game didn't exit in the meantime (since we set the game connection attribute to None when it exits). We should check this wherever we need the game connection and at least gracefully log a warning.

**Comment by GrotheFAF** [comment]
I commented on that early on:
http://forums.faforever.com/search.php?keywords=AttributeError%3A+%27NoneType%27+&t=11611

I have this error on nearly all first games after client start and sometimes inbetween (since that infamous february surprise to this day)
