### ISSUE TITLE
URLs to maps sometimes contain spaces

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#771]
We have cases where the client code passes pretty-printed names of maps to download functions, causing spaces to appear in links instead of underscores. This breaks downloading some maps.

This can be easily and hackily fixed for the time being, and the fix should be cherrypicked to stable. We will make a proper cleanup of map name usage that fixes this issue later.

**Comment by duk3luk3** [comment]
What needs to happen is instead of guessing the filename of maps is to throw away the map vault php script and do a clean implementation based on the api, which has all the information from the map tables.
