### ISSUE TITLE
finished live replays cant be loaded

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/client#783]
**I experienced...** this error in the stable release 0.13.2+2070:
![grafik](https://user-images.githubusercontent.com/21953792/28087631-6d91b3de-6683-11e7-8b3e-6343081528fe.png)

**how to reproduce** search for replays in the vault and find a live game (in "playing" state), then wait until the game ends and try to launch the replay without refreshing the list

**I expected...** loading the normal replay file

**Where the bug is / What should be done** handle the finished live games correctly

**Comment by GrotheFAF** [comment]
That the 'playing' games are shown in Replays, is a bug or feature?.
The replay list does not refresh automatically.
So if a 'playing' game ended between search and click, that's what happens.
To hit search again would be to easy... 
I will see if that can be bend torwards no error-msg.

**Comment by GrotheFAF** [comment]
sorry the code didn't won the moronic beauty contest so .. no fix.

**Comment by CookieNoob** [comment]
thats really unfortunate :/
