### ISSUE TITLE
little box to tick in unit database of un-stable client

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#810]
![image](https://user-images.githubusercontent.com/11618427/28536096-e1da4aee-70a6-11e7-86c7-497269bb2228.png)
what it looks like

![image](https://user-images.githubusercontent.com/11618427/28536102-ea6d6484-70a6-11e7-9f88-fe05cb664455.png)
what it should look like

**Comment by Wesmania** [comment]
The unitDB was replaced, so I'm closing this for now.
