### ISSUE TITLE
friend aren't all at the top of name list in aeolus

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#813]
![image](https://user-images.githubusercontent.com/11618427/28630870-c0cfbb6e-722b-11e7-8216-c71d675883d2.png)
![image](https://user-images.githubusercontent.com/11618427/28630896-d6023b7e-722b-11e7-91f2-f005fe81ac46.png)

in unstable client

**Comment by GrotheFAF** [comment]
I have that too, not all the time, often times directly after client start.
It seems the list is fine first and then some friends drop down in list. (when I change to Chat tab the first time after start)

**Comment by Wesmania** [comment]
I did some work that ensures the chatter is sorted properly after update in my new-object-model branch. I can try porting some of this work to 0.16.0.

**Comment by GrotheFAF** [comment]
another case: when I canceled a map-download while join-game from chat, the list twitched and got scrambled, some handfull of seconds later it sortet itself out (new-object-model - not cause finding?)

**Comment by Wesmania** [comment]
Hmm, map downloading shouldn't affect players in any way whatsoever, so maybe it's unrelated. How did it get scrambled? Completely?

**Comment by GrotheFAF** [comment]
2 groups of a few friends dropped down a few places in list. (so not all friends, about half were in the 2 groups)
and what I canceled wasn't just a map download, with that I also canceled a FA start.
and it was not reproducable (tried it many times), so could be a conicidence.

**Comment by GrotheFAF** [comment]
last 'good commit': 'Add changelog entry for #663'
first (functioning) breaking commit: 'Factor off widgety part from GameItem'

**Comment by GrotheFAF** [comment]
this can be closed
