### ISSUE TITLE
uncaught exception when downloading maps

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/client#824]
**I experienced...** an error when I tried to download a map (specifically Adaptive Proteus)

```
Traceback (most recent call last):
  File "src\vault\__init__.py", line 192, in downloadMap
  File "src\fa\maps.py", line 127, in link2name
IndexError: list index out of range

Runtime info:

FAF Username: CookieNoob
FAF Version: 0.13.2+2070
FAF Environment: production
FAF Directory: C:\ProgramData\FAForever
FA Path: : C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance
Home Directory: C:\Users\SirTobi\Documents

```

**Comment by duk3luk3** [comment]
@Wesmania you touched that code last :-)

**Comment by CookieNoob** [comment]
I think the map wasnt properly uploaded (map upload is kinda broken in downlords client and the fix uploaded a broken map), anyway that case should be handled too

**Comment by CookieNoob** [comment]
there are 3 maps already that cause this exception:
![grafik](https://user-images.githubusercontent.com/21953792/29118265-811f1ad8-7d01-11e7-90e2-57bb31eab236.png)

**Comment by Wesmania** [comment]
Yeah, seems it's a problem with download link missing a '/maps' prefix. I can fix it up for now so it doesn't throw a bare exception.

**Comment by duk3luk3** [comment]
I fixed the maps on the server so this shouldn't occur anymore for now.

**Comment by muellni** [comment]
Probably related: https://github.com/FAForever/faf-java-api/commit/c520336b86c68e20e93814e875762b4518e4f45c

**Comment by duk3luk3** [comment]
closing this, at it doesn't seem to be a client problem.
