### ISSUE TITLE
map preview did not show up in play and replay section

### ISSUE THREAD

**Issue by badbwoi** [FAForever/client#836]
Hey, I just uploaded 4 maps, but unfortunately the map preview did not show up in the play and replay section. Would be very nice if someone could fix this soon, or tell me what i did wrong. I was about to release the maps in the next map bundle on monday. the maps are: "Adaptive Monument Valley", "Adaptive Monument Valley Flooded", "Adaptive Sand Box" and "Adaptive Theta Passage"

![image 1](https://user-images.githubusercontent.com/28671151/29325470-19259c68-81e8-11e7-91fc-fcfc7f4d1247.png)
![image](https://user-images.githubusercontent.com/28671151/29325474-1ad32940-81e8-11e7-83ed-ce3a1e4189c4.png)

**Comment by duk3luk3** [comment]
How did you upload the maps?

**Comment by badbwoi** [comment]
Hey, I uploaded it via downlords client. But the problem was on my side and is fixed now. It could be fixed with "clear game ...". regards

**Comment by ThrashAbaddon** [comment]
@badbwoi  if problem was on your side and is fixed now then close the issue.
