### ISSUE TITLE
Enabled mods not remembered from previous games

### ISSUE THREAD

**Issue by JonnoHR31** [FAForever/client#840]
**I experienced...** When hosting a game, random mods used in the past are auto enabled, but not the mods from the previous game.

**how to reproduce** Host any game with multiple mods and then host again.

**I expected...** The client used to remember mods enabled and auto-enable the same mods the next time a game is hosted.

**Where the bug is / What should be done** In the coding somewhere? I have no idea sorry :).

**Comment by JonnoHR31** [comment]
Has this commit gone live?

**Comment by Wesmania** [comment]
It's not in any release right now, but it's commited in the repo. Actually a couple other fixes came in, so I'll go ahead and make another rc release.

**Comment by JonnoHR31** [comment]
Awesome, thank you very much :)
