### ISSUE TITLE
already hosted games are not proper set as "from friend" during client start

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#845]
so the name of your friend is grey (when it should be blue) at first, and it turns into blue which mean hosted by friend as soon as there is an update on the game being hosted.

**Comment by GrotheFAF** [comment]
from GameItem.update ... stack down:
color = client.instance.players.getUserColor(self.hostid) ->
 affil = self.user.getAffiliation(id_)
  if self.isFriend(id_, name):
   return self._friends.has(id_)
     return value in self._relations  <- empty set (when the initial games are set on client start, later it's filled according to friend,foe,clanie)

**Comment by GrotheFAF** [comment]
That behaviour existed already in 0.13.2/0.14.0
It seems to be a race condition, between user/chat/game processing after client start ...
don't we all love async ;-)
