### ISSUE TITLE
Use jinja as a parser for client strings

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#851]
I was touching tooltip formatting code and came up with an idea. Python allows us to define custom formatters - if we implemented one that allows us to express loops, conditionals and member access, we could both simplify the code and make strings vastly more themeable. We could use something like {player.login} for member access, {%if is_me%}...{%else%}...{%endif%} for conditionals and {%for player in players%}...{%endfor%} for loops.

**Comment by duk3luk3** [comment]
You're describing jinja.

And I don't think we should use that unless we really need it.

**Comment by Wesmania** [comment]
Yeah, I wasn't aware of it. Let's make this about using jinja for things then.
