### ISSUE TITLE
Map downloader ignores 404 error, downloads error page as a png

### ISSUE THREAD

**Issue by Wesmania** [FAForever/client#852]
Turns out that the map downloader does not check for a 404 somehow and instead downloads the generated 404 page as a PNG. If we fix it, missing PNGs will display the 'missing' icon properly rather than an empty icon.

**Comment by duk3luk3** [comment]
I think I've been touching that code last, I'll take a look.

**Comment by Wesmania** [comment]
If you're doing it, could you implement a timeout for failed downloads that keeps requests that failed to download once on hold for a minute or so? Game widgets update fairly often (can be even every couple of seconds) and every change to a game with a missing map preview would trigger a download attempt.
