### ISSUE TITLE
Support for list of game_info

### ISSUE THREAD

**Issue by micheljung** [FAForever/client#855]
In the current protocol, the server sends each `game_info` as a single message. This causes [squillions of messages](https://github.com/FAForever/server/blob/504a75ee80c8ee1e010e45c6350d351cab6d0efd/server/__init__.py#L101) being sent.

I'd like to reduce the number of messages by sending one message instead, containing a list of `game_info`. Just like [we're already doing it for `player_info`](https://github.com/FAForever/client/blob/d0013dab1f706075a2b0bf6e31f3f194cf6e80dc/src/client/_clientwindow.py#L1319), I propose that we **add** support for:

    {"command": "game_info", "games": [{...}, {...}]}

Once this in place, this would allow us to reduce the number of game messages sent by the server by probably 30-60x.

**Comment by Wesmania** [comment]
I don't mind this one, it could actually be convenient for the client, too. I think that hiding games for host's foes is implemented server-side, so the list is different for different players - will it cause issues or are we only interested in reducing number of messages?

**Comment by Wesmania** [comment]
Interestingly enough, we already have this exact functionality in 0.13.2 and beyond, see function handle_game_info. You can go ahead and implement it in the server and everything should just work.

**Comment by Wesmania** [comment]
Since support for this is in the client already, this is just a server issue now.
