### ISSUE TITLE
random replay vault error

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/client#857]
Traceback (most recent call last):
  File "src\replays\_replayswidget.py", line 576, in replayVault
  File "src\replays\replayitem.py", line 218, in infoPlayers
  File "src\replays\replayitem.py", line 277, in generateInfoPlayersHtml
RuntimeError: wrapped C/C++ object of type ReplayItem has been deleted
Runtime info:
FAF Username: PhilipJFry
FAF Version: 0.16.0-rc.6+74-g9ad68bcc.175
FAF Environment: production
FAF Directory: C:\ProgramData\FAForever
FA Path: : C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance
Home Directory: C:/Users/Philipp/Documents
Platform: Windows-10-10.0.15063
Uname: uname_result(system='Windows', node='Philipp-PC', release='10', version='10.0.15063', machine='AMD64', processor='Intel64 Family 6 Model 60 Stepping 3, GenuineIntel')

not sure how to reproduce
i got the error while looking for replays of a specific user

**Comment by duk3luk3** [comment]
Your client version is not an officially released version, please talk directly to the person you got that client from or reproduce the problem with a released version.

**Comment by PhilipJFryFAF** [comment]
looks like the bug did occur again 
http://forums.faforever.com/viewtopic.php?f=3&t=15158

**Comment by ghost** [comment]
Got it too sometimes, from the thread + from what I saw, it seems like it is more likely to happen when you have a slow connection.

**Comment by duk3luk3** [comment]
Probably ReplayItems (entries in replay list) get deleted when switching away from tab or doing similar things that clear / change replay list, and a replayinfo update comes later - this should no longer occur once replay info is taken from java api, which I am working on.
