### ISSUE TITLE
clan tag can format user name (written in bold)

### ISSUE THREAD

**Issue by Washeh** [FAForever/client#858]
Our new clan tag [<3] is incorrectly displayed, so that only [NAME is written (instead of [<3]NAME), but in bold instead

http://i.imgur.com/NTPoXbE.png

client version 0.16.0-rc.6+151

**Comment by duk3luk3** [comment]
Hi, please stop using that client version and upgrade to 0.16.0-rc.2 from the main repo. If you changed the updater url in your "FAF Lobby.ini" you need to undo that change.

**Comment by Wesmania** [comment]
I'm planning a general cleanup of the chat widget, so I'll fix this one eventually.

**Comment by Wesmania** [comment]
Chat rewrite was merged in, and I've seen the tag displayed properly.
