### ISSUE TITLE
missing sound effect

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/client#865]
there used to be a sound effect when someone sent you a pm in the irc (works in 0.14.0)
but there is no such thing in 0.16.0

**Comment by duk3luk3** [comment]
Please check your notification settings

**Comment by PhilipJFryFAF** [comment]
![image](https://user-images.githubusercontent.com/24656673/31432913-28e33dd8-ae78-11e7-82c6-9b4a6f61b5a1.png)
![image](https://user-images.githubusercontent.com/24656673/31433927-2898cdf4-ae7b-11e7-9a96-e7b94acba2e7.png)

still no sound for me

**Comment by speed2CZ** [comment]
I have the same problem on both my pc and laptop
Also few ppl already PMed me with that.
Here's my log, just forced few ppl to PM me...
[forever.log](https://github.com/FAForever/client/files/1386404/forever.log)

**Comment by PhilipJFryFAF** [comment]
should be fixed by #995
