### ISSUE TITLE
Client's window is always open

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/client#867]
Clicking the client's icon in the taskbar doesn't minimize it.
The only way to do this is via Win-D to shot the desktop. But then if I click on any other open window the client will pop up as well.

Only if I click the (-) icon to minimize it, it works as intended.

**Comment by Wesmania** [comment]
AFAIK the client has its own convoluted minimize / maximize code (and for a good reason, since qt stuff is bugged, since underlying Windows / X stuff is bugged). I'll look into it.

**Comment by micheljung** [comment]
Fixed in JavaFX 13
