### ISSUE TITLE
Coop - remove sup com linking

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/client#876]
Can you remove the button that asks for supreme commander from coop tab?
http://puu.sh/ykGww/a21471d61a.png

Also the last sentence that you need it to play vanilla campaigns can go, since everything works just with FA.

**Comment by Wesmania** [comment]
It should be a trivial change, but did you verify that having just FA is installed is enough? That'd be weird IMO, are we distributing assets for the original supcom campaign like character videos and voices?

**Comment by speed2CZ** [comment]
yes I verified it

**Comment by Wesmania** [comment]
I pushed a PR for this, I think I removed all the code related to linking vanilla SupCom. Please test it.
