### ISSUE TITLE
error the file wasnt properly sent by server

### ISSUE THREAD

**Issue by ghost** [FAForever/client#887]
I have no clue on how they have this issue (maybe permission ?) or how to reproduce but they seem like some have this issue. It would be nice that the client is able to fix it itself instead of the user fixing it manually.

It seems like it can maybe be solved by by clearing the game files.

**Comment by TAGUtter** [comment]
You not the only , others are having same problems too ,lets wait for a fix or understand if the reason might be because win10 updates and  i think this is not happend to all players that reinstall faf.

Downloard client gives a java error, FAF data its not send to server.

**Comment by duk3luk3** [comment]
This is a server issue. I've fixed it manually for the latest fafmod files and it will be fixed properly soon.
