### ISSUE TITLE
Can't know easily the ladder maps pool from client 

### ISSUE THREAD

**Issue by ghost** [FAForever/client#889]
You can't see when you want to play a ladder game the different maps available for it (unless you do some dirty solution for example search on vault 1v1 ladder replays and find the maps...)

It would be nice to have a preview of all the maps somewhere near the start ladder button (could be a button show map or something). I heard it was possible before but not anymore.

**Comment by GrotheFAF** [comment]
See #882, the problem was to get the data from server.
(to search ladder replays will have the problem of unknown map pool change dates)
but ... if the api is able to deliver the pool....

**Comment by Wesmania** [comment]
I merged Grothe's PR that adds a menu link to the forum thread. It should suffice for now, I think, but let's keep this open until we get the api solution.

**Comment by GrotheFAF** [comment]
We could add (the same link) to the ladder explain text in Play, would be 'closer' and more visible.

**Comment by GrotheFAF** [comment]
this can be closed, right?

**Comment by ghost** [comment]
Yeah kinda, but I think later it should be better than opening a web page and show all the pages nicely on the client. That's why I didn't do put fixes #889 in the pr

**Comment by GrotheFAF** [comment]
ok, but this is 'literally' aside from the topic.... if I understand it right.

**Comment by Wesmania** [comment]
Hmm, I promised earlier not to close it before be merge a solution that uses the API. I think it won't hurt to keep it open.
