### ISSUE TITLE
lose the 'as..' part of Import Xwidget as X

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#894]
I think it's clearer, less confusing and consistend to refer to widgets as widgets.

example:
from stats.__init__:
from ._statswidget import StatsWidget as Stats
in _clientwindow:
self.ladder = stats.Stats(self)

would be clearer:
from ._statswidget import StatsWidget
self.ladder = stats.StatsWidget(self)

Discuss ...

**Comment by Wesmania** [comment]
+1

**Comment by GrotheFAF** [comment]
There are 2 cases of 'instance' that are used all over:
client\__init__: instance = ClientWindow()
fa\game_process: instance = GameProcess()

might be usefull to rename the later to: game_instance = GameProcess()
