### ISSUE TITLE
Wrong number of players in the list of games in play tab

### ISSUE THREAD

**Issue by ghost** [FAForever/client#896]
The number of players shown in the games in play tab can be wrong when a player is in obs : 

For example if you host a 8 players map, have 7 players in slots and 1 obs, it will show 8/8 whereas it should show 7/8. I am not totally sure if it is client side or no. Haven't looked yet.

**Comment by Wesmania** [comment]
It's not a client bug - we faithfully display what the server tells us, and this info doesn't come from host's client, but from lobby.
