### ISSUE TITLE
#newbie chat channel autojoin

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#899]
http://forums.faforever.com/viewtopic.php?f=2&t=15555

I have registered a channel for newbies. Would it be possible to have players with less than (for example) 50 games played autojoined to this channel?

**Comment by Viba** [comment]
_chatwidget.py line 64, adding #newbie there makes everyone using python client autojoin.
Include filter for amount of games with "self.number_of_games" if #newbie should be added or not?

**Comment by JaggedAppliance** [comment]
https://github.com/FAForever/client/pull/357

Perhaps this could be salvaged?

**Comment by ghost** [comment]
Yes salvaged it. Don't know what the criteria should be used to distinguish newbie or not.. so I used deviation (like the game lobby with the white rating) : deviation > 100 (on ladder or global) => considered newbie

EDIT : Nevermind, using deviation is highly related to the number of games but someone who only play ladder or global will always be considered newbie.. so switching to number of games, I guess 50?
