### ISSUE TITLE
Notify when messages are sent in non-aeolus channels

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/client#904]
As the title states, with the new newbie channel especially this would be very helpful.

**Comment by ghost** [comment]
You mean everytime there is a new message you want to be notified?
I feel like it may become spammy (for example an user write multiples lines in a row, or there is a discussion ongoing...) you will receive way too many notifications. 
Or you thought of something else ? Or only certain messages?

**Comment by JaggedAppliance** [comment]
What I was thinking about was just the taskbar icon turning yellow as it does when you are pinged and having the clan/newbie/tourney chat tab flash in the client when there is a new message. right now there's no indication so it's impossible to easily keep up with multiple channels, you have to click into each to actually see if people are posting.

**Comment by Wesmania** [comment]
We added a 'new message' icons to chat tabs, so I'll consider this one fixed.
