### ISSUE TITLE
internal affair - function naming

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/client#908]
I see different functions - Qt, python - with the same name, that is confusing.

example: autoJoin in _clientwindow is a QtSignal, while _chatwidget it's a python function.

I would suggest to make python functions (and variabes) lower case, and keep the mixed case to Qt stuff.

**Comment by Wesmania** [comment]
Sure, why not. As far as I can see your PR doesn't touch things potentially touched by the ICE branch, so we'll merge it after I double-check stuff.
