### ISSUE TITLE
crossed swords in chat list linking to old replays

### ISSUE THREAD

**Issue by tobias-strenger** [FAForever/client#920]
crossed swords are linking to an old replay (which is not loadeable)

eg user: ThePwnable

Replay: 7089130. End time is missing

I assume it depends on the missing end time.

**Comment by Wesmania** [comment]
This is unfortunately more of a server issue - it's not easy to tell when a player stopped playing a game, in particular he's not registered as having finished playing if he keeps FA open after the game ends. The same game is probably also visible in the live replay tab. There's nothing in the client we can do about this for now, we'd need to report game end to the server, and that will involve both game and server code.
