### ISSUE TITLE
Lobby Lag/hang time.

### ISSUE THREAD

**Issue by killer-turnus** [FAForever/client#98]
While the FAF lobby is open, my entire computer seems retarded. Multitasking is a pain (not even in game mind you) and forget watching videos. Anyway the lock ups (programs stop responding) seems to happen consistently every 10-15 minutes especially when im using my browser or watching something on the side. The rest of the time there is a stuttery lag when watching videos. Closing FAF seems to end the problem

It confuses me because i didn't think the chat used that much memory/cpu.

**Comment by arkitect-dev** [comment]
not really anything specific to go on here and it's not clear if it's something the faf client is doing or graphics drivers etc. this can't really be progressed so closing
