### ISSUE TITLE
online vault : 1 game isn't mark as finished

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#988]
![image](https://user-images.githubusercontent.com/11618427/36639321-2b231bd2-1a56-11e8-9367-44f73508c739.png)
space4man and mountain have 2 on going games on the online vault
[forever.log](https://github.com/FAForever/client/files/1755810/forever.log)
2nd screenshot : ![image](https://user-images.githubusercontent.com/11618427/36639336-8a521176-1a56-11e8-8d0f-2e07e84d2886.png)

**Comment by shalkya** [comment]
also double clicking on the red rock one, launched the theta one (as a live replay).
[forever.log](https://github.com/FAForever/client/files/1755812/forever.log)
[replay.log](https://github.com/FAForever/client/files/1755813/replay.log)

3rd screenshot : 
![image](https://user-images.githubusercontent.com/11618427/36639415-b62ea858-1a57-11e8-84a3-5d2219e1a8f0.png)

also when i want to see the red rock one now, i get this message : 
![image](https://user-images.githubusercontent.com/11618427/36639419-ddb4da14-1a57-11e8-9d51-da82a4b1c529.png)
[forever.log](https://github.com/FAForever/client/files/1755816/forever.log)

you can also note that the 2nd one seems to have start before the 1st one finished (look at game duration, and start time) OR the server didn't register the end of the first game, and that's why both games had their duration increasing from the 1st to the 2nd screenshot (in which case 1st game duration is equal to 31:33 - 16:55 = 14:38)

**Comment by shalkya** [comment]
update : i'm now able to watch the game (wasn't possible before)
content.faforever.com/faf/vault/replay_vault/replay.php?id=7543581
it end up at 14:32
![image](https://user-images.githubusercontent.com/11618427/36643266-b2f439e0-1a94-11e8-9332-16d5092376b2.png)
with no loser/winner (which is weird)

**Comment by Wesmania** [comment]
I think it should be considered a server issue.
