### ISSUE TITLE
map in the lobby preview always comeback to the 1st of the list after refaf

### ISSUE THREAD

**Issue by shalkya** [FAForever/client#992]
used to be the previous map that has been set in the preview, that will be the one by default. 
It still does that after you change the map in the lobby preview while not refafing.
Though now when you refaf, instead of loading the previous one by default, it is the 1st map, of your map list. 
which is annoying when you are used to host the same map a lot. (eg : i like to host seton's a lot to do all my testing)
![image](https://user-images.githubusercontent.com/11618427/36876069-de209056-1dfe-11e8-8950-557cf8a33c57.png)

**Comment by Wesmania** [comment]
I have a fix queued up. For the sake of simplicity, the default map would now always be the one that the last hosted game was run with, rather than the last selected option. I think it will be good enough.
